# Generated by Django 5.0.6 on 2026-05-06 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cogsentry',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['marketplace', 'date'], name='ix_daily_me_marketp_f569d4_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['date'], name='ix_daily_me_date_9f4cbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymetric',
            unique_together={('marketplace', 'date')},
        ),
        migrations.AddField(
            model_name='monthlytarget',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ppccampaignsnapshot',
            index=models.Index(fields=['marketplace', 'date'], name='ix_ppc_snap_marketp_7b526e_idx'),
        ),
        migrations.AddIndex(
            model_name='ppccampaignsnapshot',
            index=models.Index(fields=['campaign_id'], name='ix_ppc_snap_campaig_8837b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ppccampaignsnapshot',
            unique_together={('marketplace', 'date', 'campaign_id')},
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorysnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='dashboard.product'),
        ),
        migrations.AddField(
            model_name='cogsentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cogs_entries', to='dashboard.product'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['marketplace', 'is_read'], name='ix_alerts_marketp_1d2fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'is_resolved'], name='ix_alerts_severit_5c4656_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlytarget',
            unique_together={('marketplace', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('asin', 'marketplace')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorysnapshot',
            unique_together={('product', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='cogsentry',
            unique_together={('product', 'month')},
        ),
    ]
