# Generated by Django 5.0.6 on 2026-05-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_fbafeerate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PPCProductSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                ("date", models.DateField()),
                ("asin", models.CharField(max_length=16)),
                ("sku", models.CharField(blank=True, max_length=64)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("sp", "Sponsored Products"),
                            ("sd", "Sponsored Display"),
                            ("sb", "Sponsored Brands"),
                        ],
                        default="sp",
                        max_length=4,
                    ),
                ),
                ("impressions", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sales_7d",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("orders_7d", models.IntegerField(default=0)),
                ("units_7d", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ix_ppc_product_snapshots",
                "ordering": ["-date", "-spend"],
            },
        ),
        migrations.RenameIndex(
            model_name="fbafeerate",
            new_name="ix_fba_fee__product_27107c_idx",
            old_name="ix_fba_fee_r_product_idx",
        ),
        migrations.AlterField(
            model_name="fbafeerate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="ppcproductsnapshot",
            index=models.Index(
                fields=["marketplace", "date"], name="ix_ppc_prod_marketp_6fbd8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ppcproductsnapshot",
            index=models.Index(fields=["asin"], name="ix_ppc_prod_asin_a003ba_idx"),
        ),
        migrations.AddIndex(
            model_name="ppcproductsnapshot",
            index=models.Index(fields=["sku"], name="ix_ppc_prod_sku_3da924_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="ppcproductsnapshot",
            unique_together={("marketplace", "date", "asin", "campaign_type")},
        ),
    ]
