# Generated by Django 5.0.6 on 2026-06-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_ppc_product_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySkuSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, max_length=8)),
                ('date', models.DateField(db_index=True)),
                ('sku', models.CharField(max_length=64)),
                ('asin', models.CharField(blank=True, max_length=16)),
                ('qty', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amz_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fulfill', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cm', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ix_daily_sku_snapshot',
                'indexes': [models.Index(fields=['marketplace', 'date'], name='ix_daily_sk_marketp_39ee89_idx')],
                'unique_together': {('marketplace', 'date', 'sku')},
            },
        ),
    ]
