# Generated by Django 5.0.6 on 2026-06-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_hourly_snapshots"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="hourlymetricsnapshot",
            new_name="ix_hourly_m_marketp_41d3f7_idx",
            old_name="ix_hms_mp_d_h_idx",
        ),
        migrations.RenameIndex(
            model_name="hourlymetricsnapshot",
            new_name="ix_hourly_m_date_aed8fa_idx",
            old_name="ix_hms_date_idx",
        ),
        migrations.RenameIndex(
            model_name="hourlyskusnapshot",
            new_name="ix_hourly_s_marketp_4cc09c_idx",
            old_name="ix_hss_mp_d_h_idx",
        ),
        migrations.RenameIndex(
            model_name="hourlyskusnapshot",
            new_name="ix_hourly_s_marketp_94bc1d_idx",
            old_name="ix_hss_mp_sku_d_idx",
        ),
        migrations.AlterField(
            model_name="hourlymetricsnapshot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="hourlyskusnapshot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
