# Generated by Django 5.0.6 on 2026-06-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_ads_sync_log_and_sp_hourly"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdsStreamSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                (
                    "dataset_id",
                    models.CharField(
                        choices=[
                            (
                                "sp-traffic",
                                "SP Traffic (impressions / clicks / cost per minute)",
                            ),
                            (
                                "sp-conversion",
                                "SP Conversion (orders / sales, attribution-windowed)",
                            ),
                            ("sb-traffic", "SB Traffic"),
                            ("sb-conversion", "SB Conversion"),
                            ("sd-traffic", "SD Traffic"),
                            ("sd-conversion", "SD Conversion"),
                            ("budget-usage", "Budget Usage (% budget consumed)"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subscription_id", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE — pushing events"),
                            ("FAILED_PROVISIONING", "FAILED_PROVISIONING"),
                            ("ARCHIVED", "ARCHIVED — stopped"),
                            ("UNKNOWN", "UNKNOWN — never refreshed from API"),
                        ],
                        default="UNKNOWN",
                        max_length=24,
                    ),
                ),
                ("delivery_stream_arn", models.CharField(blank=True, max_length=256)),
                ("subscription_role_arn", models.CharField(blank=True, max_length=256)),
                ("subscriber_role_arn", models.CharField(blank=True, max_length=256)),
                (
                    "s3_bucket",
                    models.CharField(
                        blank=True,
                        help_text="S3 bucket the Firehose writes to",
                        max_length=128,
                    ),
                ),
                (
                    "s3_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Prefix Firehose uses inside the bucket",
                        max_length=256,
                    ),
                ),
                ("last_status_check", models.DateTimeField(blank=True, null=True)),
                (
                    "last_ingest_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the consumer processed an object for this sub",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ix_ads_stream_subscription",
            },
        ),
        migrations.CreateModel(
            name="AmsProcessedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                ("s3_bucket", models.CharField(max_length=128)),
                ("s3_key", models.CharField(max_length=1024)),
                ("object_size", models.BigIntegerField(default=0)),
                (
                    "records_parsed",
                    models.IntegerField(
                        default=0,
                        help_text="Total inner AMS records found in the object",
                    ),
                ),
                (
                    "records_used",
                    models.IntegerField(
                        default=0,
                        help_text="Records that mapped to a known dataset and got aggregated",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ix_ams_processed_object",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="adsdatasynclog",
            new_name="ix_ads_data_marketp_fd9637_idx",
            old_name="ix_adsd_mp_date_idx",
        ),
        migrations.RenameIndex(
            model_name="adsdatasynclog",
            new_name="ix_ads_data_marketp_08c98c_idx",
            old_name="ix_adsd_mp_d_s_idx",
        ),
        migrations.RenameIndex(
            model_name="adsdatasynclog",
            new_name="ix_ads_data_status_cf72ab_idx",
            old_name="ix_adsd_status_idx",
        ),
        migrations.RenameIndex(
            model_name="ppccampaignhourlysnapshot",
            new_name="ix_ppc_camp_marketp_f9cc57_idx",
            old_name="ix_ppch_mp_d_h_idx",
        ),
        migrations.RenameIndex(
            model_name="ppccampaignhourlysnapshot",
            new_name="ix_ppc_camp_marketp_04a785_idx",
            old_name="ix_ppch_mp_camp_d_idx",
        ),
        migrations.RenameIndex(
            model_name="ppccampaignhourlysnapshot",
            new_name="ix_ppc_camp_date_2ff7e7_idx",
            old_name="ix_ppch_date_hour_idx",
        ),
        migrations.AlterField(
            model_name="adsdatasynclog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ppccampaignhourlysnapshot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="adsstreamsubscription",
            index=models.Index(
                fields=["marketplace", "dataset_id"],
                name="ix_ads_stre_marketp_7f1189_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adsstreamsubscription",
            index=models.Index(fields=["status"], name="ix_ads_stre_status_4acded_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="adsstreamsubscription",
            unique_together={("marketplace", "dataset_id")},
        ),
        migrations.AddIndex(
            model_name="amsprocessedobject",
            index=models.Index(
                fields=["marketplace", "-processed_at"],
                name="ix_ams_proc_marketp_1c8f33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amsprocessedobject",
            index=models.Index(
                fields=["s3_bucket", "s3_key"], name="ix_ams_proc_s3_buck_6e4f52_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="amsprocessedobject",
            unique_together={("s3_bucket", "s3_key")},
        ),
    ]
