# Generated by Django 5.0.6 on 2026-06-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_ams_subscription_and_processed_object"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adsstreamsubscription",
            unique_together=set(),
        ),
    ]
