# Generated by Django 5.0.6 on 2026-06-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_relax_stream_subscription_unique"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ppccampaignhourlysnapshot",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="ppccampaignhourlysnapshot",
            name="campaign_type",
            field=models.CharField(
                default="sp",
                help_text="'sp' | 'sb' | 'sd' — populated from AMS event dataset_id",
                max_length=4,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ppccampaignhourlysnapshot",
            unique_together={
                ("marketplace", "date", "hour", "campaign_id", "campaign_type")
            },
        ),
    ]
