# Generated by Django 5.0.6 on 2026-06-11 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_ppc_hourly_include_campaign_type_in_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ppccampaignhourlysnapshot",
            name="source",
            field=models.CharField(
                choices=[
                    ("ams", "Amazon Marketing Stream (real-time push)"),
                    ("manual", "Manual upload (Seller Central hourly export)"),
                ],
                default="ams",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="AdsManualHourlyUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("sp", "Sponsored Products"),
                            ("sb", "Sponsored Brands"),
                            ("sd", "Sponsored Display"),
                        ],
                        max_length=2,
                    ),
                ),
                ("original_filename", models.CharField(max_length=256)),
                ("date_range_start", models.DateField(blank=True, null=True)),
                ("date_range_end", models.DateField(blank=True, null=True)),
                ("rows_in_file", models.IntegerField(default=0)),
                (
                    "rows_imported",
                    models.IntegerField(
                        default=0, help_text="(campaign, hour) buckets upserted"
                    ),
                ),
                ("days_covered", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK — rows imported"),
                            ("failed", "Failed — see error"),
                        ],
                        default="ok",
                        max_length=12,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ams_manual_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ix_ads_manual_hourly_upload",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["marketplace", "-uploaded_at"],
                        name="ix_ads_manu_marketp_b3933a_idx",
                    ),
                    models.Index(
                        fields=["ad_type"], name="ix_ads_manu_ad_type_30ccfc_idx"
                    ),
                ],
            },
        ),
    ]
