# Generated by Django 5.0.6 on 2026-06-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_manual_hourly_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkuPpcAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                ("date", models.DateField(help_text="Marketplace local TZ")),
                ("sku", models.CharField(max_length=64)),
                ("asin", models.CharField(max_length=16)),
                ("campaign_id", models.CharField(max_length=64)),
                ("campaign_type", models.CharField(max_length=4)),
                (
                    "campaign_spend",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Input — campaign total for the day",
                        max_digits=12,
                    ),
                ),
                (
                    "asin_weight",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Pass 1 weight (0–1)",
                        max_digits=8,
                    ),
                ),
                (
                    "sku_weight",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Pass 2 weight (0–1)",
                        max_digits=8,
                    ),
                ),
                (
                    "sku_ppc_spend",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "revenue_t7_sku",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "revenue_t30_sku",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "revenue_t7_asin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "revenue_t30_asin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "attribution_source",
                    models.CharField(
                        choices=[
                            (
                                "sp_advertised_product",
                                "SP (authoritative spAdvertisedProduct report)",
                            ),
                            ("sb_revenue_share", "SB (target-set revenue mix)"),
                            ("sd_revenue_share", "SD (target-set revenue mix)"),
                            (
                                "group_revenue_share",
                                "Fallback (product-group revenue mix)",
                            ),
                            (
                                "sp_provisional",
                                "Provisional (carry yesterday's ASIN weights)",
                            ),
                            ("cold_start_equal", "Cold-start (equal split, new ASIN)"),
                            (
                                "cold_start_catalog",
                                "Cold-start (catalog price share, new SKU)",
                            ),
                            (
                                "reconciled",
                                "Residual reconciled to match campaign spend",
                            ),
                            ("unallocated", "Could not be mapped — held aside"),
                        ],
                        default="unallocated",
                        max_length=28,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="0.00 (low) to 1.00 (high)",
                        max_digits=3,
                    ),
                ),
                (
                    "settlement_state",
                    models.CharField(
                        choices=[
                            ("provisional", "Provisional — data still arriving"),
                            ("settling", "Settling — within T+3 window"),
                            ("locked", "Locked — immutable"),
                        ],
                        default="provisional",
                        max_length=12,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ix_sku_ppc_allocation",
                "ordering": ["-date", "marketplace", "sku"],
                "indexes": [
                    models.Index(
                        fields=["marketplace", "-date", "sku"],
                        name="ix_sku_ppc_dash_idx",
                    ),
                    models.Index(
                        fields=["settlement_state", "-date"],
                        name="ix_sku_ppc_state_idx",
                    ),
                    models.Index(
                        fields=["date", "campaign_id"], name="ix_sku_ppc_recon_idx"
                    ),
                ],
                "unique_together": {
                    ("marketplace", "date", "sku", "asin", "campaign_id")
                },
            },
        ),
    ]
