# Generated by Django 5.0.6 on 2026-06-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0017_sku_ppc_allocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsdatasynclog",
            name="source",
            field=models.CharField(
                choices=[
                    ("sp_hourly", "SP Hourly (Ads API timeUnit=HOURLY)"),
                    ("sb_daily", "SB Daily Campaign Report"),
                    ("sd_daily", "SD Daily Campaign Report"),
                    ("orders", "SP-API Orders Hourly"),
                    ("sp_search_term_daily", "SP Search Term Daily"),
                    ("sb_search_term_daily", "SB Search Term Daily"),
                    ("sp_targeting_daily", "SP Targeting Daily"),
                    ("sb_targeting_daily", "SB Targeting Daily"),
                    ("sd_targeting_daily", "SD Targeting Daily"),
                    ("sp_advertised_product_daily", "SP Advertised Product Daily"),
                    ("sb_advertised_product_daily", "SB Purchased Product Daily"),
                    ("sd_advertised_product_daily", "SD Advertised Product Daily"),
                    ("sp_placement_daily", "SP Placement Daily"),
                    ("sb_placement_daily", "SB Placement Daily"),
                    ("sp_adgroup_daily", "SP Ad Group Daily"),
                    ("sb_adgroup_daily", "SB Ad Group Daily"),
                    ("sd_adgroup_daily", "SD Ad Group Daily"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AdsAdGroupDailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                ("date", models.DateField()),
                (
                    "source_ad_type",
                    models.CharField(
                        choices=[
                            ("sp", "Sponsored Products"),
                            ("sb", "Sponsored Brands"),
                            ("sd", "Sponsored Display"),
                        ],
                        max_length=4,
                    ),
                ),
                ("campaign_id", models.CharField(max_length=64)),
                ("ad_group_id", models.CharField(max_length=64)),
                ("ad_group_name", models.CharField(blank=True, max_length=256)),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("orders_7d", models.IntegerField(default=0)),
                (
                    "sales_7d",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("units_7d", models.IntegerField(default=0)),
                (
                    "acos",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "roas",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("ctr", models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ("cvr", models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ("cpc", models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ix_ads_adgroup_daily",
                "ordering": ["-date", "marketplace", "-spend"],
                "indexes": [
                    models.Index(
                        fields=["marketplace", "-date"],
                        name="ix_ads_adgr_marketp_74ca64_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "campaign_id", "-date"],
                        name="ix_ads_adgr_marketp_5a19ce_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "marketplace",
                        "date",
                        "source_ad_type",
                        "campaign_id",
                        "ad_group_id",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="AdsAdvertisedProductDailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                ("date", models.DateField()),
                (
                    "source_ad_type",
                    models.CharField(
                        choices=[
                            ("sp", "Sponsored Products"),
                            ("sb", "Sponsored Brands"),
                            ("sd", "Sponsored Display"),
                        ],
                        max_length=4,
                    ),
                ),
                ("campaign_id", models.CharField(max_length=64)),
                (
                    "ad_group_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("asin", models.CharField(max_length=16)),
                (
                    "advertised_sku",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Amazon-reported SKU; may be empty for SB purchasedProduct.",
                        max_length=64,
                    ),
                ),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("orders_7d", models.IntegerField(default=0)),
                (
                    "sales_7d",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("units_7d", models.IntegerField(default=0)),
                (
                    "ba_click_share",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "ba_conversion_share",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "ba_purchase_share",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                ("ba_search_volume_rank", models.IntegerField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ix_ads_advertised_product_daily",
                "ordering": ["-date", "marketplace", "-spend"],
                "indexes": [
                    models.Index(
                        fields=["marketplace", "-date"],
                        name="ix_ads_adve_marketp_d361bf_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "campaign_id", "-date"],
                        name="ix_ads_adve_marketp_758892_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "asin", "-date"],
                        name="ix_ads_adve_marketp_7c0e27_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "advertised_sku", "-date"],
                        name="ix_ads_adve_marketp_87a238_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "marketplace",
                        "date",
                        "source_ad_type",
                        "campaign_id",
                        "asin",
                        "advertised_sku",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="AdsPlacementDailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                ("date", models.DateField()),
                (
                    "source_ad_type",
                    models.CharField(
                        choices=[
                            ("sp", "Sponsored Products"),
                            ("sb", "Sponsored Brands"),
                            ("sd", "Sponsored Display"),
                        ],
                        max_length=4,
                    ),
                ),
                ("campaign_id", models.CharField(max_length=64)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("top_of_search", "Top of Search"),
                            ("rest_of_search", "Rest of Search"),
                            ("product_pages", "Product Pages"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("orders_7d", models.IntegerField(default=0)),
                (
                    "sales_7d",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("units_7d", models.IntegerField(default=0)),
                (
                    "acos",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "roas",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ix_ads_placement_daily",
                "ordering": ["-date", "marketplace", "-spend"],
                "indexes": [
                    models.Index(
                        fields=["marketplace", "-date"],
                        name="ix_ads_plac_marketp_702cc5_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "campaign_id", "-date"],
                        name="ix_ads_plac_marketp_4498eb_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "marketplace",
                        "date",
                        "source_ad_type",
                        "campaign_id",
                        "placement",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="AdsSearchTermDailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                ("date", models.DateField()),
                (
                    "source_ad_type",
                    models.CharField(
                        choices=[
                            ("sp", "Sponsored Products"),
                            ("sb", "Sponsored Brands"),
                            ("sd", "Sponsored Display"),
                        ],
                        max_length=4,
                    ),
                ),
                ("campaign_id", models.CharField(max_length=64)),
                ("ad_group_id", models.CharField(max_length=64)),
                (
                    "target_id",
                    models.CharField(
                        help_text="The keyword/target the search term matched against.",
                        max_length=64,
                    ),
                ),
                ("match_type", models.CharField(blank=True, default="", max_length=12)),
                ("search_term", models.CharField(max_length=512)),
                (
                    "search_term_hash",
                    models.CharField(
                        help_text="SHA1(lower(search_term)) — for fast cross-campaign joins.",
                        max_length=40,
                    ),
                ),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("orders_7d", models.IntegerField(default=0)),
                (
                    "sales_7d",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("units_7d", models.IntegerField(default=0)),
                (
                    "acos",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "roas",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("ctr", models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ("cvr", models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ("cpc", models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ix_ads_search_term_daily",
                "ordering": ["-date", "marketplace", "-spend"],
                "indexes": [
                    models.Index(
                        fields=["marketplace", "-date"],
                        name="ix_ads_sear_marketp_fae580_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "campaign_id", "-date"],
                        name="ix_ads_sear_marketp_8646b3_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "search_term_hash", "-date"],
                        name="ix_ads_sear_marketp_cd270a_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "-date", "-spend"],
                        name="ix_ads_sear_marketp_ca65f2_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "marketplace",
                        "date",
                        "source_ad_type",
                        "campaign_id",
                        "ad_group_id",
                        "target_id",
                        "search_term_hash",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="AdsTargetingDailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                ("date", models.DateField()),
                (
                    "source_ad_type",
                    models.CharField(
                        choices=[
                            ("sp", "Sponsored Products"),
                            ("sb", "Sponsored Brands"),
                            ("sd", "Sponsored Display"),
                        ],
                        max_length=4,
                    ),
                ),
                ("campaign_id", models.CharField(max_length=64)),
                ("ad_group_id", models.CharField(max_length=64)),
                ("target_id", models.CharField(max_length=64)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("keyword", "Keyword"),
                            ("product_asin", "Product Target (ASIN)"),
                            ("product_category", "Product Target (Category)"),
                            ("audience", "Audience"),
                            ("contextual", "Contextual"),
                            ("auto", "Auto Target"),
                            ("other", "Other"),
                        ],
                        default="keyword",
                        max_length=20,
                    ),
                ),
                (
                    "expression",
                    models.CharField(
                        blank=True,
                        help_text="Keyword text, ASIN, category ID, or audience expression.",
                        max_length=512,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exact", "Exact"),
                            ("phrase", "Phrase"),
                            ("broad", "Broad"),
                            ("targeted", "Targeted"),
                            ("", "—"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("orders_7d", models.IntegerField(default=0)),
                (
                    "sales_7d",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("units_7d", models.IntegerField(default=0)),
                (
                    "acos",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "roas",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("ctr", models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ("cvr", models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ("cpc", models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ix_ads_targeting_daily",
                "ordering": ["-date", "marketplace", "-spend"],
                "indexes": [
                    models.Index(
                        fields=["marketplace", "-date"],
                        name="ix_ads_targ_marketp_5981a9_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "campaign_id", "-date"],
                        name="ix_ads_targ_marketp_e6c424_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "target_type", "-date"],
                        name="ix_ads_targ_marketp_0696c6_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "marketplace",
                        "date",
                        "source_ad_type",
                        "campaign_id",
                        "ad_group_id",
                        "target_id",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                ("campaign_id", models.CharField(max_length=64)),
                ("campaign_name", models.CharField(max_length=256)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("sp", "Sponsored Products"),
                            ("sb", "Sponsored Brands"),
                            ("sd", "Sponsored Display"),
                        ],
                        default="sp",
                        max_length=4,
                    ),
                ),
                ("portfolio_id", models.CharField(blank=True, max_length=64)),
                ("portfolio_name", models.CharField(blank=True, max_length=128)),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="Parsed or manually set. Used for brand-level rollups.",
                        max_length=64,
                    ),
                ),
                (
                    "product_family",
                    models.CharField(
                        blank=True,
                        help_text='Parsed product family / line, e.g. "Bath Towel".',
                        max_length=64,
                    ),
                ),
                (
                    "initials",
                    models.CharField(
                        blank=True,
                        help_text='Short product code parsed from campaign name (e.g. "BTW").',
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Latest known state — for reference only; not authoritative.",
                        max_length=12,
                    ),
                ),
                ("first_seen_date", models.DateField(blank=True, null=True)),
                ("last_seen_date", models.DateField(blank=True, null=True)),
                ("brand_locked", models.BooleanField(default=False)),
                ("product_family_locked", models.BooleanField(default=False)),
                ("initials_locked", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ix_campaigns",
                "ordering": ["marketplace", "campaign_name"],
                "indexes": [
                    models.Index(
                        fields=["marketplace", "campaign_type"],
                        name="ix_campaign_marketp_47d398_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "brand"],
                        name="ix_campaign_marketp_3f2665_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "product_family"],
                        name="ix_campaign_marketp_265681_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "portfolio_id"],
                        name="ix_campaign_marketp_db1a9c_idx",
                    ),
                ],
                "unique_together": {("marketplace", "campaign_id")},
            },
        ),
        migrations.CreateModel(
            name="CampaignProfitDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                ("date", models.DateField()),
                ("campaign_id", models.CharField(max_length=64)),
                (
                    "source_ad_type",
                    models.CharField(
                        choices=[
                            ("sp", "Sponsored Products"),
                            ("sb", "Sponsored Brands"),
                            ("sd", "Sponsored Display"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ad_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("attributed_units", models.IntegerField(default=0)),
                ("attributed_orders", models.IntegerField(default=0)),
                (
                    "cogs_attributed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "referral_fee_attributed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "fba_fee_attributed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "other_fees_attributed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "contribution_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "gross_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "margin_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "tacos",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "acos",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "roas",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                ("sku_count_attributed", models.IntegerField(default=0)),
                (
                    "attribution_coverage_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="0–100; how much of campaign sales matched to advertised-product rows.",
                        max_digits=5,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ix_campaign_profit_daily",
                "ordering": ["-date", "-gross_profit"],
                "indexes": [
                    models.Index(
                        fields=["marketplace", "-date"],
                        name="ix_campaign_marketp_e71dee_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "campaign_id", "-date"],
                        name="ix_campaign_marketp_b282dd_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "-date", "-gross_profit"],
                        name="ix_campaign_marketp_deaabe_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "-date", "-margin_pct"],
                        name="ix_campaign_marketp_d88cbe_idx",
                    ),
                ],
                "unique_together": {("marketplace", "date", "campaign_id")},
            },
        ),
        migrations.CreateModel(
            name="CampaignSearchTermSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                ("date", models.DateField()),
                ("campaign_id", models.CharField(max_length=64)),
                (
                    "source_ad_type",
                    models.CharField(
                        choices=[
                            ("sp", "Sponsored Products"),
                            ("sb", "Sponsored Brands"),
                            ("sd", "Sponsored Display"),
                        ],
                        max_length=4,
                    ),
                ),
                ("distinct_terms", models.IntegerField(default=0)),
                ("high_spend_no_sales", models.IntegerField(default=0)),
                ("high_ctr_low_cvr", models.IntegerField(default=0)),
                ("losing_money", models.IntegerField(default=0)),
                ("scaling_opportunity", models.IntegerField(default=0)),
                ("high_profit", models.IntegerField(default=0)),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                (
                    "spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sales_7d",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("orders_7d", models.IntegerField(default=0)),
                (
                    "wasted_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ix_campaign_search_term_summary",
                "ordering": ["-date", "marketplace", "-spend"],
                "indexes": [
                    models.Index(
                        fields=["marketplace", "-date"],
                        name="ix_campaign_marketp_108a76_idx",
                    ),
                    models.Index(
                        fields=["marketplace", "campaign_id", "-date"],
                        name="ix_campaign_marketp_82faab_idx",
                    ),
                ],
                "unique_together": {("marketplace", "date", "campaign_id")},
            },
        ),
    ]
