# Generated by Django 5.0.6 on 2026-06-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_phase1_campaign_intelligence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsdatasynclog',
            name='source',
            field=models.CharField(choices=[('sp_hourly', 'SP Hourly (Ads API timeUnit=HOURLY)'), ('sb_daily', 'SB Daily Campaign Report'), ('sd_daily', 'SD Daily Campaign Report'), ('orders', 'SP-API Orders Hourly'), ('sp_search_term_daily', 'SP Search Term Daily'), ('sb_search_term_daily', 'SB Search Term Daily'), ('sp_targeting_daily', 'SP Targeting Daily'), ('sb_targeting_daily', 'SB Targeting Daily'), ('sd_targeting_daily', 'SD Targeting Daily'), ('sp_advertised_product_daily', 'SP Advertised Product Daily'), ('sb_advertised_product_daily', 'SB Purchased Product Daily'), ('sd_advertised_product_daily', 'SD Advertised Product Daily'), ('sp_placement_daily', 'SP Placement Daily'), ('sb_placement_daily', 'SB Placement Daily'), ('sp_adgroup_daily', 'SP Ad Group Daily'), ('sb_adgroup_daily', 'SB Ad Group Daily'), ('sd_adgroup_daily', 'SD Ad Group Daily'), ('ba_search_query_weekly', 'BA Search Query Performance Weekly'), ('ba_item_comparison_weekly', 'BA Item Comparison Weekly'), ('ba_market_basket_weekly', 'BA Market Basket Weekly')], max_length=32),
        ),
        migrations.AlterField(
            model_name='adsplacementdailysnapshot',
            name='placement',
            field=models.CharField(choices=[('top_of_search', 'Top of Search'), ('product_pages', 'Product Pages'), ('other_on_amazon', 'Other on-Amazon (incl. Rest of Search, Cart, etc.)'), ('off_amazon', 'Off Amazon (Partner / Affiliate sites)'), ('rest_of_search', 'Rest of Search (legacy)'), ('other', 'Other (legacy)')], max_length=20),
        ),
        migrations.CreateModel(
            name='BABrandShareWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=8)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('brand', models.CharField(help_text='Brand name as stored in Product.brand — same casing.', max_length=64)),
                ('avg_click_share', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('avg_conversion_share', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('avg_purchase_share', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('queries_we_appear_in', models.IntegerField(default=0)),
                ('queries_we_dominate', models.IntegerField(default=0, help_text='Queries where we hold the #1 click slot.')),
                ('weighted_click_share', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('weighted_purchase_share', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('total_query_volume', models.BigIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ix_ba_brand_share_weekly',
                'ordering': ['-week_start', 'marketplace', 'brand'],
                'indexes': [models.Index(fields=['marketplace', '-week_start'], name='ix_ba_brand_marketp_ec5989_idx'), models.Index(fields=['marketplace', 'brand', '-week_start'], name='ix_ba_brand_marketp_1fae39_idx')],
                'unique_together': {('marketplace', 'week_start', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='BAItemComparisonWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=8)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('asin', models.CharField(help_text='Our ASIN being compared FROM.', max_length=16)),
                ('compared_asin', models.CharField(help_text='Competitor / alternate ASIN.', max_length=16)),
                ('compared_title', models.CharField(blank=True, max_length=512)),
                ('compared_frequency_rank', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ix_ba_item_comparison_weekly',
                'ordering': ['-week_start', 'asin', 'compared_frequency_rank'],
                'indexes': [models.Index(fields=['marketplace', '-week_start'], name='ix_ba_item__marketp_140a45_idx'), models.Index(fields=['marketplace', 'asin', '-week_start'], name='ix_ba_item__marketp_568bf4_idx'), models.Index(fields=['marketplace', 'compared_asin', '-week_start'], name='ix_ba_item__marketp_9af31b_idx')],
                'unique_together': {('marketplace', 'week_start', 'asin', 'compared_asin')},
            },
        ),
        migrations.CreateModel(
            name='BAMarketBasketWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=8)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('asin', models.CharField(help_text='Our ASIN being purchased.', max_length=16)),
                ('purchased_asin', models.CharField(help_text='Co-purchased ASIN (any brand).', max_length=16)),
                ('purchased_title', models.CharField(blank=True, max_length=512)),
                ('purchased_frequency_rank', models.IntegerField(default=0, help_text='1 = most-co-purchased.')),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ix_ba_market_basket_weekly',
                'ordering': ['-week_start', 'asin', 'purchased_frequency_rank'],
                'indexes': [models.Index(fields=['marketplace', '-week_start'], name='ix_ba_marke_marketp_f03ff9_idx'), models.Index(fields=['marketplace', 'asin', '-week_start'], name='ix_ba_marke_marketp_914085_idx'), models.Index(fields=['marketplace', 'purchased_asin', '-week_start'], name='ix_ba_marke_marketp_2dd00f_idx')],
                'unique_together': {('marketplace', 'week_start', 'asin', 'purchased_asin')},
            },
        ),
        migrations.CreateModel(
            name='BASearchQueryWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=8)),
                ('week_start', models.DateField(help_text='Monday (start of week)')),
                ('week_end', models.DateField(help_text='Sunday (end of week)')),
                ('search_query', models.CharField(max_length=512)),
                ('search_query_hash', models.CharField(help_text='SHA1(lower(search_query)) — for the unique key + cross-week joins.', max_length=40)),
                ('search_query_score', models.IntegerField(default=0, help_text='Amazon search frequency rank — lower = more popular.')),
                ('search_query_volume', models.BigIntegerField(default=0, help_text='Total impressions Amazon saw for this query in the week.')),
                ('impressions_total', models.BigIntegerField(default=0)),
                ('impressions_asin_count', models.IntegerField(default=0)),
                ('clicks_total', models.BigIntegerField(default=0)),
                ('cart_adds_total', models.BigIntegerField(default=0)),
                ('purchases_total', models.BigIntegerField(default=0)),
                ('brand_impressions_share', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('brand_click_share', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('brand_cart_add_share', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('brand_purchase_share', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('top_clicked_asins', models.JSONField(default=list, help_text='[{asin, brand?, click_share, title?}, ...] — up to 3 items.')),
                ('top_converted_asins', models.JSONField(default=list, help_text='[{asin, brand?, conversion_share, title?}, ...] — up to 3 items.')),
                ('top_purchased_asins', models.JSONField(default=list, help_text='[{asin, brand?, purchase_share, title?}, ...] — up to 3 items.')),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ix_ba_search_query_weekly',
                'ordering': ['-week_start', 'search_query_score'],
                'indexes': [models.Index(fields=['marketplace', '-week_start'], name='ix_ba_searc_marketp_f019ee_idx'), models.Index(fields=['marketplace', 'search_query_hash', '-week_start'], name='ix_ba_searc_marketp_1978fa_idx'), models.Index(fields=['marketplace', '-week_start', 'search_query_score'], name='ix_ba_searc_marketp_bc90fd_idx')],
                'unique_together': {('marketplace', 'week_start', 'search_query_hash')},
            },
        ),
    ]
