# Generated by Django 5.0.6 on 2026-06-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_phase3_brand_analytics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basearchqueryweekly',
            options={'ordering': ['-week_start', 'asin', 'search_query_score']},
        ),
        migrations.AlterUniqueTogether(
            name='basearchqueryweekly',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='basearchqueryweekly',
            name='asin',
            field=models.CharField(default='', help_text='Amazon now requires SQP reports to be ASIN-scoped — each (week × ASIN) yields one report, and each report can list many queries. We persist asin so the per-query share rollup knows which of our ASINs this row belongs to.', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='basearchqueryweekly',
            unique_together={('marketplace', 'week_start', 'asin', 'search_query_hash')},
        ),
        migrations.AddIndex(
            model_name='basearchqueryweekly',
            index=models.Index(fields=['marketplace', 'asin', '-week_start'], name='ix_ba_searc_marketp_e092ff_idx'),
        ),
    ]
