# Generated by Django 5.0.6 on 2026-06-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_ba_search_query_per_asin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adsdatasynclog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='adsdatasynclog',
            name='asin',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='adsdatasynclog',
            unique_together={('marketplace', 'date', 'source', 'asin')},
        ),
    ]
