# Generated by Django 5.0.6 on 2026-06-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_ads_data_sync_log_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='basearchqueryweekly',
            name='asin_cart_add_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basearchqueryweekly',
            name='asin_click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basearchqueryweekly',
            name='asin_impression_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basearchqueryweekly',
            name='asin_purchase_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basearchqueryweekly',
            name='brand_cart_add_share',
            field=models.DecimalField(decimal_places=4, default=0, help_text='% of all query cart-adds our ASIN got (0-100).', max_digits=7),
        ),
        migrations.AlterField(
            model_name='basearchqueryweekly',
            name='brand_click_share',
            field=models.DecimalField(decimal_places=4, default=0, help_text='% of all query clicks our ASIN got (0-100).', max_digits=7),
        ),
        migrations.AlterField(
            model_name='basearchqueryweekly',
            name='brand_impressions_share',
            field=models.DecimalField(decimal_places=4, default=0, help_text='% of all query impressions our ASIN got (0-100).', max_digits=7),
        ),
        migrations.AlterField(
            model_name='basearchqueryweekly',
            name='brand_purchase_share',
            field=models.DecimalField(decimal_places=4, default=0, help_text='% of all query purchases our ASIN got (0-100).', max_digits=7),
        ),
    ]
