# Generated by Django 5.0.6 on 2026-06-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_ba_sqp_real_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamarketbasketweekly',
            name='combination_pct',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Amazon-reported combination probability (0-1).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='adsdatasynclog',
            name='source',
            field=models.CharField(choices=[('sp_hourly', 'SP Hourly (Ads API timeUnit=HOURLY)'), ('sb_daily', 'SB Daily Campaign Report'), ('sd_daily', 'SD Daily Campaign Report'), ('orders', 'SP-API Orders Hourly'), ('sp_search_term_daily', 'SP Search Term Daily'), ('sb_search_term_daily', 'SB Search Term Daily'), ('sp_targeting_daily', 'SP Targeting Daily'), ('sb_targeting_daily', 'SB Targeting Daily'), ('sd_targeting_daily', 'SD Targeting Daily'), ('sp_advertised_product_daily', 'SP Advertised Product Daily'), ('sb_advertised_product_daily', 'SB Purchased Product Daily'), ('sd_advertised_product_daily', 'SD Advertised Product Daily'), ('sp_placement_daily', 'SP Placement Daily'), ('sb_placement_daily', 'SB Placement Daily'), ('sp_adgroup_daily', 'SP Ad Group Daily'), ('sb_adgroup_daily', 'SB Ad Group Daily'), ('sd_adgroup_daily', 'SD Ad Group Daily'), ('ba_search_query_weekly', 'BA Search Query Performance Weekly'), ('ba_item_comparison_weekly', 'BA Item Comparison Weekly (DEPRECATED)'), ('ba_market_basket_weekly', 'BA Market Basket Weekly'), ('ba_repeat_purchase_weekly', 'BA Repeat Purchase Weekly')], max_length=32),
        ),
        migrations.CreateModel(
            name='BARepeatPurchaseWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=8)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('asin', models.CharField(max_length=16)),
                ('orders', models.IntegerField(default=0)),
                ('unique_customers', models.IntegerField(default=0)),
                ('repeat_customers_pct', models.DecimalField(decimal_places=6, default=0, help_text='% of customers who bought 2+ times (0-1).', max_digits=8)),
                ('repeat_purchase_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('repeat_purchase_revenue_pct', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ix_ba_repeat_purchase_weekly',
                'ordering': ['-week_start', '-orders'],
                'indexes': [models.Index(fields=['marketplace', '-week_start'], name='ix_ba_repea_marketp_4e4db3_idx'), models.Index(fields=['marketplace', 'asin', '-week_start'], name='ix_ba_repea_marketp_4259b5_idx')],
                'unique_together': {('marketplace', 'week_start', 'asin')},
            },
        ),
    ]
