# Generated by Django 5.0.6 on 2026-06-14 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_ba_repeat_purchase_market_basket_combo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=8)),
                ('generated_at', models.DateTimeField()),
                ('reference_date', models.DateField(help_text='The "yesterday" anchor the AI was looking at.')),
                ('recommendation_id', models.CharField(db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('critical', 'Critical — act today'), ('warning', 'Warning — act this week'), ('opportunity', 'Opportunity — scale candidate'), ('info', 'Info')], default='info', max_length=12)),
                ('category', models.CharField(choices=[('ppc_scale', 'PPC: scale budget'), ('ppc_cut', 'PPC: cut budget'), ('ppc_negate', 'PPC: negate term'), ('ppc_bid', 'PPC: adjust bid'), ('sku_scale', 'SKU: push harder'), ('sku_pause', 'SKU: pause / deprioritise'), ('margin_fix', 'Margin: fix margin compression'), ('inventory', 'Inventory action'), ('listing', 'Listing / PDP optimisation'), ('cross_sell', 'Cross-sell / bundle'), ('competitive', 'Competitive response'), ('other', 'Other')], default='other', max_length=20)),
                ('scope_type', models.CharField(choices=[('campaign', 'Campaign'), ('sku', 'SKU / product'), ('search_term', 'Search term'), ('placement', 'Placement'), ('brand', 'Brand-level'), ('account', 'Account-level'), ('inventory', 'Inventory'), ('other', 'Other')], default='account', max_length=16)),
                ('scope_id', models.CharField(blank=True, help_text='campaign_id / sku / search_term — blank for account-level.', max_length=64)),
                ('scope_name', models.CharField(blank=True, help_text='Human-readable label to surface in the UI.', max_length=256)),
                ('headline', models.CharField(help_text='The action in one short sentence — what to do.', max_length=256)),
                ('evidence', models.TextField(blank=True, help_text='The data that supports the recommendation (numbers, deltas).')),
                ('suggested_action', models.TextField(blank=True, help_text='Concrete next step — what the user should change.')),
                ('projected_impact', models.CharField(blank=True, help_text='Estimated $ impact / week, or a qualitative band.', max_length=128)),
                ('rank_score', models.DecimalField(decimal_places=2, default=0, help_text='Compound score — severity × impact × confidence. Used for sort.', max_digits=6)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, help_text='0.00 (low) to 1.00 (high).', max_digits=3)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('done', 'Done'), ('snoozed', 'Snoozed'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=14)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True, help_text='Optional user comment when marking done/dismissed.')),
                ('ai_model', models.CharField(blank=True, max_length=64)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Full structured JSON the AI returned, for debugging.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recs_acknowledged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ix_ai_recommendations',
                'ordering': ['-rank_score', '-generated_at'],
                'indexes': [models.Index(fields=['marketplace', 'status', '-rank_score'], name='ix_ai_recom_marketp_7df51f_idx'), models.Index(fields=['marketplace', '-generated_at'], name='ix_ai_recom_marketp_107a43_idx'), models.Index(fields=['marketplace', 'scope_type', 'scope_id'], name='ix_ai_recom_marketp_6c6a71_idx')],
                'unique_together': {('marketplace', 'recommendation_id')},
            },
        ),
    ]
