# Generated by Django 5.0.6 on 2026-06-16 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_phase4_ai_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, max_length=8)),
                ('report_id', models.CharField(help_text="Amazon's reportId", max_length=64)),
                ('document_id', models.CharField(blank=True, max_length=128)),
                ('start_date', models.DateField(blank=True, help_text='Settlement period start (UTC)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Settlement period end (UTC)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'Ok'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('rows_processed', models.IntegerField(default=0)),
                ('fee_rows', models.IntegerField(default=0, help_text='Subset that produced FBA per-unit fulfillment fee rows.')),
                ('error_message', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ix_settlement_reports',
                'ordering': ['-end_date', '-synced_at'],
                'indexes': [models.Index(fields=['marketplace', '-end_date'], name='ix_settleme_marketp_36ab2b_idx')],
                'unique_together': {('marketplace', 'report_id')},
            },
        ),
        migrations.CreateModel(
            name='SkuFeeActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, max_length=8)),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('date', models.DateField(db_index=True, help_text='posted-date from the settlement report (when the transaction settled, not when the order was placed).')),
                ('units', models.IntegerField(default=0)),
                ('fba_fee_total', models.DecimalField(decimal_places=4, default=0, help_text='Sum of |amount| where amount-description == FBAPerUnitFulfillmentFee for this SKU on this date.', max_digits=14)),
                ('fee_per_unit', models.DecimalField(decimal_places=4, default=0, help_text='= fba_fee_total / units. Pre-computed for fast reads.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_settlement', models.ForeignKey(blank=True, help_text='The settlement report this row was extracted from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_fee_actuals', to='dashboard.settlementreport')),
            ],
            options={
                'db_table': 'ix_sku_fee_actuals',
                'ordering': ['marketplace', 'sku', '-date'],
                'indexes': [models.Index(fields=['marketplace', '-date'], name='ix_sku_fee__marketp_cd0f1d_idx'), models.Index(fields=['marketplace', 'sku', '-date'], name='ix_sku_fee__marketp_ff5041_idx')],
                'unique_together': {('marketplace', 'sku', 'date')},
            },
        ),
    ]
