# Generated by Django 5.0.6 on 2026-06-16 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_fba_drift_settlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPnLUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, max_length=8)),
                ('month', models.DateField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=256)),
                ('rows_imported', models.IntegerField(default=0)),
                ('lines_matched', models.IntegerField(default=0)),
                ('lines_unmatched', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('failed', 'Failed')], default='ok', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ix_manual_pnl_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementLineActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, max_length=8)),
                ('month', models.DateField(help_text='First day of month (posted-date basis)')),
                ('line_key', models.CharField(help_text="pnl_lines key, e.g. 'gross_sales','commission','fba_fee'", max_length=48)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Native-currency magnitude for this line in this month.', max_digits=16)),
                ('units', models.IntegerField(default=0, help_text='Unit count where meaningful (gross_sales→sold, returns→returned).')),
                ('currency', models.CharField(default='USD', max_length=4)),
                ('source_note', models.CharField(blank=True, help_text="e.g. 'settlement' or 'operational_fallback'.", max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ix_settlement_line_actuals',
                'ordering': ['marketplace', '-month', 'line_key'],
                'indexes': [models.Index(fields=['marketplace', '-month'], name='ix_settleme_marketp_fcb641_idx')],
                'unique_together': {('marketplace', 'month', 'line_key')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyFXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of month')),
                ('currency', models.CharField(help_text='ISO code, e.g. GBP, EUR, AED', max_length=4)),
                ('rate_to_usd', models.DecimalField(decimal_places=6, help_text='Multiply native amount by this to get USD.', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ix_monthly_fx_rates',
                'ordering': ['-month', 'currency'],
                'unique_together': {('month', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyPnLEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, max_length=8)),
                ('month', models.DateField(help_text='First day of month')),
                ('channel', models.CharField(choices=[('amazon', 'Amazon'), ('retail', 'Retail / Walmart')], default='amazon', max_length=8)),
                ('line_key', models.CharField(help_text='pnl_lines key for a source=manual line.', max_length=48)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Native-currency amount (positive magnitude).', max_digits=16)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ix_monthly_pnl_entries',
                'ordering': ['marketplace', '-month', 'channel', 'line_key'],
                'indexes': [models.Index(fields=['marketplace', '-month', 'channel'], name='ix_monthly__marketp_d4a174_idx')],
                'unique_together': {('marketplace', 'month', 'channel', 'line_key')},
            },
        ),
    ]
