# Generated by Django 5.0.6 on 2026-07-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_pnl_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, max_length=8)),
                ('month', models.DateField(help_text='First day of the report month')),
                ('payout_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ix_amazon_payouts',
                'ordering': ['marketplace', '-payout_date'],
                'indexes': [models.Index(fields=['marketplace', 'month'], name='ix_amazon_p_marketp_68747f_idx')],
            },
        ),
    ]
