# Generated by Django 5.0.6 on 2026-07-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_amazon_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypnlentry',
            name='invoice',
            field=models.FileField(blank=True, help_text='Optional supporting invoice/receipt for records.', null=True, upload_to='pnl_invoices/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='monthlypnlentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Native-currency amount (signed — negatives allowed for credits).', max_digits=16),
        ),
        migrations.AlterField(
            model_name='monthlypnlentry',
            name='note',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
