# Generated by Django 5.0.6 on 2026-07-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_pnl_entry_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedSkuUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, max_length=8)),
                ('month', models.DateField(help_text='First day of the report month')),
                ('sku', models.CharField(max_length=64)),
                ('order_units', models.IntegerField(default=0)),
                ('refund_units', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ix_unified_sku_units',
                'indexes': [models.Index(fields=['marketplace', 'month'], name='ix_unified__marketp_a8c593_idx')],
                'unique_together': {('marketplace', 'month', 'sku')},
            },
        ),
    ]
