# Generated by Django 5.0.6 on 2026-07-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_unified_sku_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="McfOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(db_index=True, max_length=8)),
                ("seller_order_id", models.CharField(max_length=64)),
                ("displayable_order_id", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(blank=True, db_index=True, max_length=32)),
                ("received_date", models.DateTimeField(blank=True, null=True)),
                ("recipient_name", models.CharField(blank=True, max_length=128)),
                ("city", models.CharField(blank=True, max_length=64)),
                ("state", models.CharField(blank=True, max_length=32)),
                ("units", models.IntegerField(default=0)),
                ("items", models.JSONField(blank=True, default=list)),
                ("packages", models.JSONField(blank=True, default=list)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ix_mcf_orders",
                "ordering": ["-received_date"],
                "indexes": [
                    models.Index(
                        fields=["marketplace", "-received_date"],
                        name="ix_mcf_orde_marketp_f9194e_idx",
                    )
                ],
                "unique_together": {("marketplace", "seller_order_id")},
            },
        ),
    ]
