# Generated by Django 5.0.6 on 2026-07-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0030_mcf_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymetric",
            name="revenue_net",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
