# Generated by Django 5.0.6 on 2026-07-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0031_dailymetric_revenue_net"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlementlineactual",
            name="breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
