# Generated by Django 5.0.6 on 2026-08-07 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0032_settlementlineactual_breakdown"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                (
                    "initials",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Campaign.initials codes that belong to this group, e.g. ["BTH"]. Routes ad spend in.',
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Product.category values that belong to this group. Routes ASINs / SKUs in.",
                    ),
                ),
                (
                    "extra_asins",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Manual additions — ASINs the category rule misses.",
                    ),
                ),
                (
                    "excluded_asins",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Manual subtractions — applied after every other rule.",
                    ),
                ),
                (
                    "lexicon_key",
                    models.CharField(
                        default="towel",
                        help_text="Which intent lexicon applies (apps.dashboard.sti.lexicon).",
                        max_length=32,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ix_sti_product_group",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SearchTermTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                (
                    "search_term_hash",
                    models.CharField(
                        help_text="SHA1(lower(term)) — same recipe as AdsSearchTermDailySnapshot.search_term_hash, so the two join without a text comparison.",
                        max_length=40,
                    ),
                ),
                ("search_term", models.CharField(max_length=512)),
                ("tags", models.JSONField(default=dict)),
                (
                    "lexicon_version",
                    models.IntegerField(
                        default=1,
                        help_text="Bumping LEXICON_VERSION invalidates every row.",
                    ),
                ),
                ("classified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ix_sti_search_term_tag",
                "indexes": [
                    models.Index(
                        fields=["marketplace", "lexicon_version"],
                        name="ix_sti_sear_marketp_5e2e7f_idx",
                    )
                ],
                "unique_together": {("marketplace", "search_term_hash")},
            },
        ),
        migrations.CreateModel(
            name="StiOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Stable across runs — see class docstring.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                (
                    "opp_type",
                    models.CharField(
                        choices=[
                            ("capture_share", "Capture share"),
                            ("product_gap", "Product gap"),
                            ("organic_push", "Organic push"),
                            ("listing_fix", "Listing fix"),
                            ("scale_ppc", "Scale PPC"),
                            ("defend", "Defend (waste)"),
                            ("conquest", "Conquest"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("why", models.TextField(blank=True, default="")),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The term / node / SKU this is about.",
                        max_length=512,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Expected contribution margin per month. THE ranking key.",
                        max_digits=12,
                    ),
                ),
                (
                    "headroom_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Attainable incremental revenue per month, before probability.",
                        max_digits=14,
                    ),
                ),
                (
                    "win_probability",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "margin_factor",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        default=3, help_text="1 (PPC-only) … 5 (new product)"
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="low",
                        max_length=6,
                    ),
                ),
                (
                    "blocked_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Non-empty when a hard gate fired (stockout, no margin).",
                        max_length=120,
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Every number cited in the UI, so the card is auditable.",
                    ),
                ),
                ("required_actions", models.JSONField(blank=True, default=list)),
                ("dependencies", models.JSONField(blank=True, default=list)),
                ("timeline", models.CharField(blank=True, default="", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("dismissed", "Dismissed"),
                            ("expired", "Expired"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("status_note", models.TextField(blank=True, default="")),
                (
                    "runs_unseen",
                    models.IntegerField(
                        default=0,
                        help_text="Consecutive runs where the generator no longer emitted it.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="dashboard.productgroup",
                    ),
                ),
            ],
            options={
                "db_table": "ix_sti_opportunity",
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="StiReportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=8)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("schema_version", models.IntegerField(default=1)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("duration_ms", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sti_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="dashboard.productgroup",
                    ),
                ),
            ],
            options={
                "db_table": "ix_sti_report_run",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="StiOpportunitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "headroom_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "current_share",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Our share of the market pool, 0-100.",
                        max_digits=7,
                    ),
                ),
                ("difficulty", models.IntegerField(default=3)),
                ("confidence", models.CharField(default="low", max_length=6)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="dashboard.stiopportunity",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_snapshots",
                        to="dashboard.stireportrun",
                    ),
                ),
            ],
            options={
                "db_table": "ix_sti_opportunity_snapshot",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="stiopportunity",
            name="first_seen_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities_first_seen",
                to="dashboard.stireportrun",
            ),
        ),
        migrations.AddField(
            model_name="stiopportunity",
            name="last_seen_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities_last_seen",
                to="dashboard.stireportrun",
            ),
        ),
        migrations.AddIndex(
            model_name="stireportrun",
            index=models.Index(
                fields=["product_group", "marketplace", "-generated_at"],
                name="ix_sti_repo_product_a1e5c4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stiopportunitysnapshot",
            unique_together={("opportunity", "run")},
        ),
        migrations.AddIndex(
            model_name="stiopportunity",
            index=models.Index(
                fields=["product_group", "marketplace", "status", "-score"],
                name="ix_sti_oppo_product_682973_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stiopportunity",
            index=models.Index(
                fields=["opp_type", "-score"], name="ix_sti_oppo_opp_typ_da71f9_idx"
            ),
        ),
    ]
