# Generated by Django 5.0.6 on 2026-08-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0033_productgroup_searchtermtag_stiopportunity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productgroup",
            name="categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Product.category values that define this group. THE definition — routes both ASINs and ad spend in.",
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="initials",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='DISPLAY ONLY — campaign initials commonly used for this group, e.g. ["BTH"]. Recorded so a report is easier to read against Seller Central. Never used to scope a query; scoping is by Product.category.',
            ),
        ),
    ]
