# Generated by Django 5.0.6 on 2026-08-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0034_alter_productgroup_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basearchqueryweekly",
            name="week_end",
            field=models.DateField(help_text="Saturday (end of week)"),
        ),
        migrations.AlterField(
            model_name="basearchqueryweekly",
            name="week_start",
            field=models.DateField(
                help_text="SUNDAY — Amazon's week runs Sunday to Saturday, and the stored data confirms it (2026-05-31 is a Sunday, week_end 2026-06-06 a Saturday). This field previously claimed Monday. Never derive the boundary from isocalendar(); anything assuming an ISO week is off by one day."
            ),
        ),
    ]
