# Generated by Django 5.0.6 on 2026-08-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0035_alter_basearchqueryweekly_week_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stiopportunity",
            name="acted_period_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The reporting period during which this was marked done — the anchor for measuring whether it worked.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="stiopportunitysnapshot",
            name="period_key",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Copied from the run. Makes a snapshot series comparable period-to-period rather than run-to-run.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="stireportrun",
            name="period_key",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="'2026-W31' or '2026-07'. Amazon's week numbering, NOT ISO — Amazon's Week 31 of 2026 is ISO week 30.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="stireportrun",
            name="period_type",
            field=models.CharField(
                default="weekly",
                help_text="weekly | monthly — see apps.dashboard.sti.periods",
                max_length=8,
            ),
        ),
    ]
