# Generated by Django 5.0.6 on 2026-08-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_stiopportunity_acted_period_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignBudgetUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('campaign_id', models.CharField(max_length=64)),
                ('budget_value', models.DecimalField(decimal_places=2, default=0, help_text='Daily budget amount for the day.', max_digits=12)),
                ('usage_pct', models.DecimalField(decimal_places=2, default=0, help_text='Peak % of daily budget consumed that day.', max_digits=7)),
                ('events', models.IntegerField(default=0, help_text='Budget-usage events folded into this row.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ix_campaign_budget_usage_daily',
                'ordering': ['-date', 'marketplace', '-usage_pct'],
                'indexes': [models.Index(fields=['marketplace', '-date'], name='ix_campaign_marketp_fc3ef8_idx')],
                'unique_together': {('marketplace', 'date', 'campaign_id')},
            },
        ),
    ]
