# Generated by Claude for P0.2 FBA Fee Intelligence Phase 2
# Migration to create FbaFeeComponent and DataKioskIngestLog tables

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_deactivate_unused_prefixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbaFeeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, max_length=8, help_text='Marketplace code (usa, uk, de, ae, sa)')),
                ('msku', models.CharField(db_index=True, max_length=128, help_text='Merchant SKU (seller-provided, or amzn.* for returns)')),
                ('date', models.DateField(db_index=True, help_text='Transaction date (day-level aggregation)')),
                ('fee_type', models.CharField(max_length=32, help_text='FEE_TYPE from query: FBA_FULFILLMENT_FEE or FBA_STORAGE_FEE')),
                ('component_name', models.CharField(db_index=True, max_length=48, help_text='FeeComponent.name (free text): BaseFbaFulfilmentFee, FuelSurcharge, LowInventoryLevelFee, etc.')),
                ('quantity', models.FloatField(default=0.0, help_text='Billed units for this component. May be 0.0 or null on adjustment rows (reclassification between components).')),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=14, help_text='Gross amount per rate card (excludes promotion, tax).')),
                ('amount_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=10, help_text='Final per-unit charge AFTER promotion and tax. Never use for packaging analysis per Section J.')),
                ('promotion_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14, help_text='Promotion discount applied (usually 0).')),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14, help_text='Tax added (usually 0 for B2B fulfillment).')),
                ('currency_code', models.CharField(default='USD', max_length=4, help_text='ISO 4217 code from Amount.currencyCode (USD, GBP, EUR, AED, SAR)')),
                ('is_amzn_generated', models.BooleanField(db_index=True, default=False, help_text='K1: msku begins with amzn. (grade-and-resell). Excluded from all impact analysis per business rule.')),
                ('is_adjustment', models.BooleanField(default=False, help_text='K2: quantity=0 or amount<0, indicating reclassification between components. Stored but excluded from rate derivation.')),
                ('query_date_range_start', models.DateField(blank=True, null=True, help_text='startDate of the Data Kiosk query this row came from.')),
                ('query_date_range_end', models.DateField(blank=True, null=True, help_text='endDate of the Data Kiosk query this row came from.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ix_fba_fee_component',
                'ordering': ['marketplace', 'msku', '-date', 'component_name'],
            },
        ),
        migrations.CreateModel(
            name='DataKioskIngestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, max_length=8)),
                ('fee_type', models.CharField(default='FBA_FULFILLMENT_FEE', max_length=32, help_text='Fee type requested: FBA_FULFILLMENT_FEE or FBA_STORAGE_FEE')),
                ('query_start_date', models.DateField()),
                ('query_end_date', models.DateField()),
                ('status', models.CharField(choices=[('queued', 'Queued — waiting to start'), ('submitted', 'Submitted — query sent to Amazon'), ('polling', 'Polling — waiting for completion'), ('parsing', 'Parsing — processing response'), ('ingesting', 'Ingesting — writing to database'), ('ok', 'OK — completed successfully'), ('partial', 'Partial — completed with warnings'), ('error', 'Error — failed'), ('cancelled', 'Cancelled — stopped by user')], db_index=True, default='queued', max_length=12)),
                ('query_id', models.CharField(blank=True, help_text='Data Kiosk Query.queryId for idempotency and resumption.', max_length=128, unique=True)),
                ('response_status', models.CharField(blank=True, help_text='Data Kiosk Query.processingStatus: IN_QUEUE, IN_PROGRESS, DONE', max_length=32)),
                ('rows_received', models.IntegerField(default=0, help_text='Total JSONL rows in the response.')),
                ('rows_inserted', models.IntegerField(default=0, help_text='Rows successfully inserted (excluding filtered/amended).')),
                ('rows_filtered_amzn', models.IntegerField(default=0, help_text='K1: amzn.* MSKUs excluded.')),
                ('rows_marked_adjustment', models.IntegerField(default=0, help_text='K2: quantity=0 or amount<0 marked as adjustment.')),
                ('rows_skipped_empty', models.IntegerField(default=0, help_text='K3: rows with no fees (skipped, not inserted).')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_stage', models.CharField(blank=True, help_text='Stage where error occurred: query, polling, parsing, ingesting', max_length=32)),
                ('note', models.TextField(blank=True)),
                ('triggered_by', models.CharField(blank=True, help_text='Who/what triggered this ingest (e.g. "cron", "user:farhan")', max_length=64)),
            ],
            options={
                'db_table': 'ix_data_kiosk_ingest_log',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fbafeecomponent',
            index=models.Index(fields=['marketplace', '-date'], name='ix_fbafeecomponent_mp_date'),
        ),
        migrations.AddIndex(
            model_name='fbafeecomponent',
            index=models.Index(fields=['marketplace', 'msku', '-date'], name='ix_fbafeecomponent_mp_sku_date'),
        ),
        migrations.AddIndex(
            model_name='fbafeecomponent',
            index=models.Index(fields=['is_amzn_generated', '-date'], name='ix_fbafeecomponent_amzn_date'),
        ),
        migrations.AddIndex(
            model_name='fbafeecomponent',
            index=models.Index(fields=['is_adjustment', '-date'], name='ix_fbafeecomponent_adj_date'),
        ),
        migrations.AddConstraint(
            model_name='fbafeecomponent',
            constraint=models.UniqueConstraint(fields=['marketplace', 'msku', 'date', 'fee_type', 'component_name'], name='ix_fbafeecomponent_unique'),
        ),
        migrations.AddIndex(
            model_name='datakioskingestlog',
            index=models.Index(fields=['marketplace', '-submitted_at'], name='ix_datakioskingestlog_mp_date'),
        ),
        migrations.AddIndex(
            model_name='datakioskingestlog',
            index=models.Index(fields=['status', '-submitted_at'], name='ix_datakioskingestlog_status_date'),
        ),
    ]
