# Generated by Django 5.0.6 on 2026-08-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_fba_components'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adactionrequest',
            new_name='ix_ad_actio_marketp_6f024c_idx',
            old_name='ix_adact_mp_status_idx',
        ),
        migrations.RenameIndex(
            model_name='adactionrequest',
            new_name='ix_ad_actio_entity__c37243_idx',
            old_name='ix_adact_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='campaignprefixmap',
            new_name='ix_campaign_active_ae749e_idx',
            old_name='ix_cpm_active_prefix_idx',
        ),
        migrations.RenameIndex(
            model_name='datakioskingestlog',
            new_name='ix_dkil_mp_date',
            old_name='ix_datakioskingestlog_mp_date',
        ),
        migrations.RenameIndex(
            model_name='datakioskingestlog',
            new_name='ix_dkil_status_date',
            old_name='ix_datakioskingestlog_status_date',
        ),
        migrations.AlterField(
            model_name='datakioskingestlog',
            name='query_id',
            field=models.CharField(blank=True, help_text='Data Kiosk Query.queryId for idempotency and resumption.', max_length=128, null=True),
        ),
    ]
