# Generated by Django 5.0.6 on 2026-08-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_fix_query_id_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbafeecomponent',
            name='fee_type',
            field=models.CharField(help_text="feeTypeName as Data Kiosk returns it — PascalCase display names, not the query enum: FbaFulfilmentFee (British spelling, one L), ReferralFee, DisposalFee, LiquidationProcessingFee, AmazonUpstreamStorageTransportationFee. Was max_length=32, which three live names already exceed (up to 38 chars); on Postgres that raises 'value too long' and fails the whole atomic ingest.", max_length=64),
        ),
    ]
