# Generated by Django 5.0.6 on 2026-07-20 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("region", models.CharField(default="usa", max_length=8)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fba", "Amazon FBA"),
                            ("awd", "Amazon AWD"),
                            ("3pl", "3PL Warehouse"),
                            ("factory", "Factory / Origin"),
                        ],
                        max_length=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["region", "kind", "code"],
            },
        ),
        migrations.CreateModel(
            name="PlanningSku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=64)),
                ("region", models.CharField(default="usa", max_length=8)),
                ("name", models.CharField(blank=True, max_length=128)),
                ("category", models.CharField(blank=True, max_length=64)),
                (
                    "sku_type",
                    models.CharField(
                        choices=[
                            ("key", "Key"),
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                        ],
                        default="secondary",
                        max_length=12,
                    ),
                ),
                ("product_status", models.CharField(blank=True, max_length=32)),
                ("product_manager", models.CharField(blank=True, max_length=64)),
                ("units_per_box", models.PositiveIntegerField(default=0)),
                ("msq", models.PositiveIntegerField(default=0)),
                ("factory_stock", models.PositiveIntegerField(default=0)),
                ("factory_production", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "sku"],
                "unique_together": {("sku", "region")},
            },
        ),
        migrations.CreateModel(
            name="InTransitShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(default="usa", max_length=8)),
                ("container_no", models.CharField(blank=True, max_length=32)),
                ("shipment_id", models.CharField(blank=True, max_length=64)),
                ("vendor", models.CharField(blank=True, max_length=64)),
                ("departure_date", models.DateField(blank=True, null=True)),
                ("eta_port", models.DateField(blank=True, null=True)),
                ("eta_destination", models.DateField(blank=True, null=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending departure"),
                            ("departed", "On the water"),
                            ("at_port", "At port"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="departed",
                        max_length=12,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=256)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbound_shipments",
                        to="inventory_planning.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["eta_destination", "eta_port"],
            },
        ),
        migrations.CreateModel(
            name="DemandInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=64)),
                ("region", models.CharField(default="usa", max_length=8)),
                ("pds", models.FloatField()),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sku", "region", "effective_from"],
                        name="inventory_p_sku_42f5b9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InTransitLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=64)),
                ("units", models.PositiveIntegerField(default=0)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory_planning.intransitshipment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["sku"], name="inventory_p_sku_08349d_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="WarehouseStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=64)),
                ("units", models.IntegerField(default=0)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("as_of", models.DateTimeField()),
                ("source", models.CharField(default="manual", max_length=16)),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="inventory_planning.warehouse",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["sku"], name="inventory_p_sku_353b1e_idx")
                ],
                "unique_together": {("warehouse", "sku")},
            },
        ),
    ]
