# Generated by Django 5.0.6 on 2026-07-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_planning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planningsku",
            name="sku_type",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
