# Generated by Django 5.0.6 on 2026-07-21 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_planning", "0002_alter_planningsku_sku_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="intransitline",
            name="received_units",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="intransitshipment",
            name="freight_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="intransitshipment",
            name="po_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="intransitshipment",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intransitshipment",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="intransitshipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("production_complete", "Production Complete"),
                    ("waiting_pickup", "Waiting for Pickup"),
                    ("in_transit", "In Transit"),
                    ("on_vessel", "On Vessel"),
                    ("at_port", "At Port"),
                    ("customs", "Customs Clearance"),
                    ("inland", "Inland Transit"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="in_transit",
                max_length=24,
            ),
        ),
    ]
