# Generated by Django 5.0.6 on 2026-07-23 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_planning", "0003_intransitline_received_units_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="POLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=64)),
                ("name", models.CharField(blank=True, max_length=128)),
                ("units_per_box", models.PositiveIntegerField(default=0)),
                ("boxes", models.PositiveIntegerField(default=0)),
                ("ordered_units", models.PositiveIntegerField(default=0)),
                ("wastage_units", models.PositiveIntegerField(default=0)),
                ("cbm_per_box", models.FloatField(default=0)),
                ("total_cbm", models.FloatField(default=0)),
                ("expected_ready_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("ready", "Ready for Allocation"),
                            ("partial", "Partially Allocated"),
                            ("allocated", "Fully Allocated"),
                            ("closed", "Closed"),
                            ("short_closed", "Short-Closed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "sku"],
            },
        ),
        migrations.CreateModel(
            name="POLineGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("category", models.CharField(max_length=64)),
                (
                    "fob_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("units_per_box", models.PositiveIntegerField(default=0)),
                ("boxes", models.PositiveIntegerField(default=0)),
                ("ordered_units", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("pcs", models.PositiveIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "category"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("country", models.CharField(blank=True, max_length=64)),
                ("contact", models.CharField(blank=True, max_length=128)),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("payment_terms", models.CharField(blank=True, max_length=64)),
                ("production_lead_days", models.PositiveIntegerField(default=90)),
                ("sea_lead_days", models.PositiveIntegerField(default=45)),
                ("port_to_wh_days", models.PositiveIntegerField(default=10)),
                ("monthly_capacity_units", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=256)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="intransitline",
            name="fnsku",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="planningsku",
            name="asin",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="planningsku",
            name="fnsku",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="planningsku",
            name="upc",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="intransitline",
            name="po_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocations",
                to="inventory_planning.poline",
            ),
        ),
        migrations.AddField(
            model_name="poline",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="inventory_planning.polinegroup",
            ),
        ),
        migrations.CreateModel(
            name="ProductionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pp_number", models.CharField(blank=True, max_length=32)),
                ("expected_ready_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("ready", "Ready for Allocation"),
                            ("partial", "Partially Allocated"),
                            ("allocated", "Fully Allocated"),
                            ("closed", "Closed"),
                            ("short_closed", "Short-Closed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="inventory_planning.polinegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["group__sort_order", "pp_number"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=64, unique=True)),
                ("order_date", models.DateField(blank=True, null=True)),
                ("expected_ready_date", models.DateField(blank=True, null=True)),
                ("payment_terms", models.CharField(blank=True, max_length=64)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("partial", "Partially Allocated"),
                            ("allocated", "Fully Allocated"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="inventory_planning.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="polinegroup",
            name="po",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="inventory_planning.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="poline",
            name="po",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="inventory_planning.purchaseorder",
            ),
        ),
        migrations.CreateModel(
            name="SupplierOpeningBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=64)),
                ("category", models.CharField(blank=True, max_length=64)),
                ("units", models.IntegerField(default=0)),
                ("as_of", models.DateField()),
                ("note", models.CharField(blank=True, max_length=128)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balances",
                        to="inventory_planning.supplier",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="poline",
            index=models.Index(fields=["sku"], name="inventory_p_sku_d0d2e3_idx"),
        ),
        migrations.AddIndex(
            model_name="supplieropeningbalance",
            index=models.Index(
                fields=["supplier", "sku"], name="inventory_p_supplie_bbbd69_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="supplieropeningbalance",
            unique_together={("supplier", "sku", "as_of")},
        ),
    ]
