# Generated by Django 5.0.6 on 2026-07-24 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_planning", "0005_fbatransfer_fbatransferline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashFlowPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(default="usa", max_length=8, unique=True)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("opening_as_of", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CashFlowEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(default="usa", max_length=8)),
                ("date", models.DateField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Inflow"), ("out", "Outflow")], max_length=4
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("container", "Container Payment"),
                            ("amazon", "Amazon Inflow"),
                            ("injection", "Funds Injection"),
                            ("freight", "Freight / Duty"),
                            ("hr", "HR Cost"),
                            ("storage", "Storage"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=128)),
                ("vendor", models.CharField(blank=True, max_length=64)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("auto_source", models.CharField(blank=True, max_length=16)),
                ("locked", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashflow_entries",
                        to="inventory_planning.intransitshipment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
                "indexes": [
                    models.Index(
                        fields=["region", "date"], name="inventory_p_region_5857c4_idx"
                    )
                ],
            },
        ),
    ]
