# Generated by Django 5.0.6 on 2026-07-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_planning", "0006_cashflowplan_cashflowentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashflowplan",
            name="pay_lead_days",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
