# Generated by Django 5.0.6 on 2026-07-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_planning", "0007_cashflowplan_pay_lead_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="intransitline",
            name="variance_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("damage", "Damage"),
                    ("short_ship", "Short-ship"),
                    ("lost", "Lost in transit"),
                    ("miscount", "Miscount"),
                    ("other", "Other"),
                ],
                max_length=16,
            ),
        ),
    ]
