# Generated by Django 5.0.6 on 2026-07-27 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_planning", "0008_intransitline_variance_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="POLineReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(default="usa", max_length=8)),
                ("units", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "po_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="inventory_planning.poline",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["po_line", "region"],
                        name="inventory_p_po_line_8e01d2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReorderSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=64)),
                ("name", models.CharField(blank=True, max_length=128)),
                ("category", models.CharField(blank=True, max_length=64)),
                ("demand_per_day", models.FloatField(default=0)),
                ("recommended_qty", models.PositiveIntegerField(default=0)),
                ("open_po_units", models.PositiveIntegerField(default=0)),
                ("on_hand_units", models.PositiveIntegerField(default=0)),
                ("transit_units", models.PositiveIntegerField(default=0)),
                (
                    "fob_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("target_ready_date", models.DateField(blank=True, null=True)),
                ("regions_detail", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("approved", "Approved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="suggested",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reorder_suggestions",
                        to="inventory_planning.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-recommended_qty"],
                "indexes": [
                    models.Index(
                        fields=["status", "sku"], name="inventory_p_status_f63709_idx"
                    )
                ],
            },
        ),
    ]
