# Generated by Django 5.0.6 on 2026-08-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_planning", "0009_polinereservation_reordersuggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="intransitline",
            name="amazon_expected_units",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="intransitline",
            name="amazon_received_units",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="intransitline",
            name="units_per_case",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="intransitshipment",
            name="amazon_status",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="intransitshipment",
            name="amazon_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intransitshipment",
            name="amazon_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
