# Generated by Django 5.0.6 on 2026-08-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_planning", "0010_intransitline_amazon_expected_units_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intransitshipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("production_complete", "Production Complete"),
                    ("waiting_pickup", "Waiting for Pickup"),
                    ("in_transit", "In Transit"),
                    ("on_vessel", "On Vessel"),
                    ("at_port", "At Port"),
                    ("customs", "Customs Clearance"),
                    ("inland", "Inland Transit"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("receiving", "Receiving at Amazon"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="in_transit",
                max_length=24,
            ),
        ),
    ]
