# Generated by Django 5.0.6 on 2026-08-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_planning", "0011_alter_intransitshipment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="intransitline",
            name="fob_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
