# Generated by Django 5.0.6 on 2026-08-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_planning', '0012_intransitline_fob_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='intransitline',
            name='opening_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='inventory_planning.supplieropeningbalance'),
        ),
        migrations.AddField(
            model_name='supplieropeningbalance',
            name='fob_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
