# Generated by Django 5.0.6 on 2026-05-06 10:04

import apps.amazon_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('usa', '🇺🇸 United States'), ('ca', '🇨🇦 Canada'), ('uk', '🇬🇧 United Kingdom'), ('de', '🇩🇪 Germany'), ('ae', '🇦🇪 UAE'), ('sa', '🇸🇦 Saudi Arabia')], max_length=8, unique=True)),
                ('label', models.CharField(help_text='Friendly name, e.g. "USA Main"', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('lwa_client_id', apps.amazon_api.models.EncryptedField(blank=True, help_text='Login With Amazon Client ID')),
                ('lwa_client_secret', apps.amazon_api.models.EncryptedField(blank=True, help_text='Login With Amazon Client Secret')),
                ('refresh_token', apps.amazon_api.models.EncryptedField(blank=True, help_text='SP-API Refresh Token')),
                ('aws_access_key', apps.amazon_api.models.EncryptedField(blank=True)),
                ('aws_secret_key', apps.amazon_api.models.EncryptedField(blank=True)),
                ('aws_role_arn', apps.amazon_api.models.EncryptedField(blank=True, help_text='IAM Role ARN for SP-API')),
                ('ads_client_id', apps.amazon_api.models.EncryptedField(blank=True, help_text='Advertising API Client ID')),
                ('ads_client_secret', apps.amazon_api.models.EncryptedField(blank=True)),
                ('ads_refresh_token', apps.amazon_api.models.EncryptedField(blank=True)),
                ('ads_profile_id', models.CharField(blank=True, help_text='Advertising profile ID (plain text)', max_length=32)),
                ('seller_id', models.CharField(blank=True, max_length=32)),
                ('marketplace_id', models.CharField(blank=True, help_text='Amazon marketplace ID, e.g. ATVPDKIKX0DER', max_length=32)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('untested', 'Untested')], default='untested', max_length=16)),
                ('last_test_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amazon API Configuration',
                'verbose_name_plural': 'Amazon API Configurations',
                'db_table': 'ix_amazon_api_config',
            },
        ),
        migrations.CreateModel(
            name='AnthropicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Primary', max_length=64)),
                ('api_key', apps.amazon_api.models.EncryptedField(help_text='Anthropic API Key (sk-ant-...)')),
                ('model', models.CharField(default='claude-sonnet-4-20250514', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ix_anthropic_config',
            },
        ),
        migrations.CreateModel(
            name='APISyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(help_text='e.g. orders, sales_traffic, campaigns', max_length=32)),
                ('date_range', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('partial', 'Partial')], max_length=16)),
                ('records', models.IntegerField(default=0)),
                ('error_msg', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ix_api_sync_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
