# Generated by Django 5.0.6 on 2026-06-01 06:16

import apps.amazon_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon_api", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("anthropic", "Anthropic (Claude)"),
                            ("openai", "OpenAI (ChatGPT)"),
                            ("gemini", "Google (Gemini)"),
                        ],
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(default="Primary", max_length=64)),
                (
                    "api_key",
                    apps.amazon_api.models.EncryptedField(
                        help_text="API Key (encrypted at rest)"
                    ),
                ),
                ("model", models.CharField(default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ix_ai_provider_config",
            },
        ),
    ]
