# Generated by Django 5.0.6 on 2026-06-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sqp", "0002_ai_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aiinsightcache",
            new_name="ix_sqp_ai_c_insight_8397cc_idx",
            old_name="ix_sqp_ai_c_type_idx",
        ),
        migrations.RenameIndex(
            model_name="aiinsightcache",
            new_name="ix_sqp_ai_c_created_4829df_idx",
            old_name="ix_sqp_ai_c_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aiinsighthistory",
            new_name="ix_sqp_ai_h_created_10e692_idx",
            old_name="ix_sqp_ai_h_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aiinsighthistory",
            new_name="ix_sqp_ai_h_user_id_c6f66c_idx",
            old_name="ix_sqp_ai_h_user_idx",
        ),
        migrations.RenameIndex(
            model_name="aiinsighthistory",
            new_name="ix_sqp_ai_h_insight_24a358_idx",
            old_name="ix_sqp_ai_h_type_idx",
        ),
        migrations.RenameIndex(
            model_name="sqpquery",
            new_name="ix_sqp_quer_total_v_be1c0f_idx",
            old_name="ix_sqp_q_total_vol_idx",
        ),
        migrations.RenameIndex(
            model_name="sqpquery",
            new_name="ix_sqp_quer_last_se_27b498_idx",
            old_name="ix_sqp_q_last_seen_idx",
        ),
        migrations.RenameIndex(
            model_name="sqpreport",
            new_name="ix_sqp_repo_marketp_e1367a_idx",
            old_name="ix_sqp_r_mp_pt_ps_idx",
        ),
        migrations.RenameIndex(
            model_name="sqpreport",
            new_name="ix_sqp_repo_status_8c180e_idx",
            old_name="ix_sqp_r_status_idx",
        ),
        migrations.RenameIndex(
            model_name="sqpsnapshot",
            new_name="ix_sqp_snap_marketp_3f9a18_idx",
            old_name="ix_sqp_s_mp_pt_ps_idx",
        ),
        migrations.RenameIndex(
            model_name="sqpsnapshot",
            new_name="ix_sqp_snap_marketp_a2013c_idx",
            old_name="ix_sqp_s_mp_asin_idx",
        ),
        migrations.RenameIndex(
            model_name="sqpsnapshot",
            new_name="ix_sqp_snap_query_i_ac57d9_idx",
            old_name="ix_sqp_s_query_idx",
        ),
        migrations.RenameIndex(
            model_name="sqpsnapshot",
            new_name="ix_sqp_snap_period__618dbd_idx",
            old_name="ix_sqp_s_vol_sort_idx",
        ),
        migrations.AlterField(
            model_name="aiinsightcache",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="aiinsighthistory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sqpquery",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sqpreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sqpsnapshot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
