"""
ingest_settlement_reports — daily ingestion of Amazon settlement reports.

Settlement reports are auto-generated by Amazon on a ~14-day pay cycle.
We list all DONE settlement reports created in a trailing window, dedupe
against what we've already ingested, download new ones, extract the
per-SKU per-unit FBA fulfilment-fee rows, and upsert into SkuFeeActual.

The drift page reads SkuFeeActual rows and compares to FBAFeeRate (the
"uploaded" value) to surface SKUs where Amazon's actual billing has
diverged from what the team has in their COGS spreadsheet.

Usage:
    # Default — all configured marketplaces, last 30 days of settlements
    python manage.py ingest_settlement_reports

    # Specific marketplace
    python manage.py ingest_settlement_reports --marketplace usa

    # Wider lookback (e.g. on first-run backfill)
    python manage.py ingest_settlement_reports --days 90

    # Re-process a specific reportId even if previously marked ok
    python manage.py ingest_settlement_reports --force-report-id 12345.67
"""
from __future__ import annotations

import logging
from collections import defaultdict
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal

from django.core.management.base import BaseCommand
from django.db import transaction

logger = logging.getLogger(__name__)


class Command(BaseCommand):
    help = 'Ingest Amazon settlement reports → SkuFeeActual.'

    def add_arguments(self, parser):
        parser.add_argument('--marketplace', default=None,
                             help='Restrict to one marketplace (default: all configured).')
        parser.add_argument('--days', type=int, default=30,
                             help='Trailing window for createdSince (default: 30).')
        parser.add_argument('--force-report-id', default=None,
                             help='Re-process this specific reportId even if already ok.')
        parser.add_argument('--dump-raw', default=None, metavar='DIR',
                             help='Save each downloaded settlement flat file as TSV '
                                  'into DIR (for parser-mapping inspection).')

    def handle(self, marketplace, days, force_report_id, dump_raw, **_):
        import csv as _csv
        import os as _os
        from collections import defaultdict
        from datetime import date as _date
        from django.conf import settings
        from apps.amazon_api.models import AmazonAPIConfig
        from apps.amazon_api.services import SPAPIClient
        from apps.dashboard.models import (
            SettlementReport, SkuFeeActual, SettlementLineActual,
        )

        if dump_raw:
            _os.makedirs(dump_raw, exist_ok=True)

        if marketplace:
            configs = AmazonAPIConfig.objects.filter(marketplace=marketplace, is_active=True)
        else:
            configs = AmazonAPIConfig.objects.filter(is_active=True)

        if not configs.exists():
            self.stdout.write(self.style.WARNING(
                'No active AmazonAPIConfig rows; nothing to do.'))
            return

        created_since_dt = datetime.now(timezone.utc) - timedelta(days=days)
        created_since    = created_since_dt.strftime('%Y-%m-%dT%H:%M:%SZ')

        total_new = 0
        total_skipped = 0
        total_failed = 0

        for cfg in configs:
            mp = cfg.marketplace
            self.stdout.write(f'\n[{mp.upper()}] Listing settlement reports '
                               f'created since {created_since} …')
            try:
                client  = SPAPIClient(cfg)
                reports = client.list_settlement_reports(created_since=created_since)
            except Exception as exc:
                self.stdout.write(self.style.ERROR(
                    f'  list_settlement_reports failed: {exc}'))
                continue

            self.stdout.write(f'  found {len(reports)} report(s)')

            for r in reports:
                report_id = r.get('reportId')
                doc_id    = r.get('reportDocumentId')
                start_iso = r.get('dataStartTime') or ''
                end_iso   = r.get('dataEndTime')   or ''
                start_d   = self._parse_iso_date(start_iso)
                end_d     = self._parse_iso_date(end_iso)

                if not (report_id and doc_id):
                    continue

                # Skip if we've already done it (unless forced)
                existing = SettlementReport.objects.filter(
                    marketplace=mp, report_id=report_id,
                ).first()
                if existing and existing.status == 'ok' \
                        and report_id != force_report_id:
                    total_skipped += 1
                    continue

                # Stub the audit row before downloading so a mid-fetch crash
                # leaves a 'pending' row we can resume from later
                audit, _ = SettlementReport.objects.update_or_create(
                    marketplace=mp,
                    report_id=report_id,
                    defaults={
                        'document_id': doc_id,
                        'start_date':  start_d,
                        'end_date':    end_d,
                        'status':      'pending',
                        'error_message': '',
                    },
                )

                try:
                    rows = client.download_settlement_report(doc_id)
                    fee_rows = SPAPIClient.extract_fba_fee_rows(rows)
                    pnl     = SPAPIClient.extract_pnl_lines(rows)
                except Exception as exc:
                    audit.status = 'failed'
                    audit.error_message = f'{type(exc).__name__}: {exc}'[:500]
                    audit.save(update_fields=['status', 'error_message', 'synced_at'])
                    self.stdout.write(self.style.ERROR(
                        f'  ✗ {report_id}: download/parse failed — {exc}'))
                    total_failed += 1
                    continue

                # Optionally dump the raw flat file for parser-mapping work
                if dump_raw and rows:
                    fname = _os.path.join(
                        dump_raw, f'settlement_{mp}_{report_id}.tsv')
                    with open(fname, 'w', newline='', encoding='utf-8') as fh:
                        w = _csv.DictWriter(fh, fieldnames=list(rows[0].keys()),
                                             delimiter='\t')
                        w.writeheader()
                        w.writerows(rows)
                    self.stdout.write(f'    ↳ dumped raw → {fname}')
                    if pnl['unmapped']:
                        self.stdout.write(self.style.WARNING(
                            f'    ↳ {len(pnl["unmapped"])} unmapped descriptions: '
                            + ', '.join(sorted(pnl['unmapped'])[:8])))

                # Aggregate by (sku, posted_date) — a single SKU can have
                # many orders posted on the same day, each with its own row
                agg: dict[tuple[str, date], dict] = defaultdict(
                    lambda: {'units': 0, 'fba_fee_total': 0.0})
                for fr in fee_rows:
                    posted = self._parse_iso_date(fr['posted_date'])
                    if not posted:
                        continue
                    key = (fr['sku'], posted)
                    agg[key]['units']         += fr['units']
                    agg[key]['fba_fee_total'] += fr['fba_fee_total']

                with transaction.atomic():
                    for (sku, posted), vals in agg.items():
                        units = vals['units']
                        fee_total = vals['fba_fee_total']
                        fee_per_unit = (fee_total / units) if units > 0 else 0
                        SkuFeeActual.objects.update_or_create(
                            marketplace=mp,
                            sku=sku,
                            date=posted,
                            defaults={
                                'units':             units,
                                'fba_fee_total':     fee_total,
                                'fee_per_unit':      fee_per_unit,
                                'source_settlement': audit,
                            },
                        )
                    # P&L line buckets → SettlementLineActual (per month/line).
                    # Settlement reports are incremental, so ADD to whatever is
                    # already stored for that month rather than overwrite.
                    native_ccy = (settings.AMAZON_MARKETPLACES.get(mp, {})
                                   .get('currency', 'USD')
                                   if hasattr(settings, 'AMAZON_MARKETPLACES') else 'USD')
                    for (month_str, line_key), vals in pnl['lines'].items():
                        try:
                            m = _date.fromisoformat(month_str + '-01')
                        except ValueError:
                            continue
                        row, _created = SettlementLineActual.objects.get_or_create(
                            marketplace=mp, month=m, line_key=line_key,
                            defaults={'amount': 0, 'units': 0,
                                       'currency': native_ccy,
                                       'source_note': 'settlement'},
                        )
                        # row.amount comes back from the DB as Decimal, while
                        # the parsed settlement value is a float — adding them
                        # raises TypeError and, because this runs inside the
                        # same transaction.atomic() as the SkuFeeActual writes
                        # above, it rolled the FEE ROWS BACK TOO. That is why
                        # the FBA "actual" fee stopped updating entirely.
                        # Convert through str so binary float error is not
                        # carried into the decimal.
                        row.amount = (row.amount or Decimal('0')) + Decimal(
                            str(round(float(vals['amount']), 2)))
                        row.units  = (row.units or 0) + int(vals['units'])
                        row.currency = native_ccy
                        row.source_note = 'settlement'
                        row.save(update_fields=['amount', 'units', 'currency',
                                                 'source_note', 'updated_at'])

                    audit.rows_processed = len(rows)
                    audit.fee_rows       = len(agg)
                    audit.status         = 'ok'
                    audit.error_message  = ''
                    audit.save(update_fields=['rows_processed', 'fee_rows',
                                               'status', 'error_message',
                                               'synced_at'])

                self.stdout.write(self.style.SUCCESS(
                    f'  ✓ {report_id} [{start_d}..{end_d}]: '
                    f'{len(rows)} rows → {len(agg)} (sku,date) fee aggregates'))
                total_new += 1

        self.stdout.write('')
        self.stdout.write(self.style.SUCCESS(
            f'DONE: new={total_new}  skipped={total_skipped}  '
            f'failed={total_failed}'))

    @staticmethod
    def _parse_iso_date(s: str) -> date | None:
        """Settlement dates → date, across Amazon's per-marketplace formats.

        Amazon LOCALISES posted-date in the settlement flat file:
            USA      2026-07-23              (ISO)
            UK/EU    23.07.2026              (DD.MM.YYYY)
        The old implementation only accepted ISO, so every non-US fee row
        failed to parse and was skipped — which is why UK/AE/SA/DE produced
        "0 (sku,date) fee aggregates" from tens of thousands of parsed rows
        while USA worked. Order matters below: dotted dates are unambiguous
        DD.MM.YYYY, and ISO is tried first so US behaviour is untouched.
        """
        if not s:
            return None
        s = s.strip()
        # 1) ISO — 'YYYY-MM-DD' or 'YYYY-MM-DDTHH:MM:SS(±ZZ|Z)'
        try:
            return date.fromisoformat(s[:10])
        except ValueError:
            pass
        # 2) Localised — take the leading date token, drop any time/zone part
        head = s.split(' ')[0].split('T')[0]
        for fmt in ('%d.%m.%Y',    # UK / EU / AE / SA
                    '%d/%m/%Y',    # some EU locales
                    '%Y/%m/%d',
                    '%d-%m-%Y'):
            try:
                return datetime.strptime(head, fmt).date()
            except ValueError:
                continue
        return None
