# Generated by Django 5.0.6 on 2026-07-13 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AmazonMCFOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fulfillment_order_id", models.CharField(max_length=48, unique=True)),
                (
                    "amazon_status",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("shipping_speed", models.CharField(default="Standard", max_length=24)),
                ("feature_constraints", models.JSONField(default=list)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("last_status_check", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Amazon MCF Order",
                "db_table": "wm_mcf_orders",
            },
        ),
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("walmart", "Walmart"), ("amazon", "Amazon")],
                        max_length=8,
                    ),
                ),
                ("endpoint", models.CharField(max_length=256)),
                ("method", models.CharField(max_length=8)),
                ("request_body", models.TextField(blank=True)),
                ("response_body", models.TextField(blank=True)),
                ("status_code", models.IntegerField(null=True)),
                ("duration_ms", models.IntegerField(default=0)),
                ("correlation_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "wm_api_logs",
            },
        ),
        migrations.CreateModel(
            name="WalmartOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_order_id", models.CharField(max_length=32, unique=True)),
                ("customer_order_id", models.CharField(blank=True, max_length=32)),
                ("marketplace", models.CharField(default="usa", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("VALIDATED", "Validated"),
                            ("PROCESSING", "Processing"),
                            ("MCF_CREATED", "MCF Created"),
                            ("SHIPPED", "Shipped"),
                            ("TRACKING_UPLOADED", "Tracking Uploaded"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                            ("HOLD", "Hold (inventory)"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=24,
                    ),
                ),
                ("order_date", models.DateTimeField()),
                ("customer_name", models.CharField(blank=True, max_length=128)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("shipping_address", models.JSONField(default=dict)),
                ("shipping_method", models.CharField(blank=True, max_length=24)),
                ("raw_order", models.JSONField(default=dict)),
                ("error_reason", models.TextField(blank=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wm_orders",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_id", models.CharField(blank=True, max_length=64)),
                ("package_number", models.IntegerField(default=0)),
                ("carrier_code", models.CharField(blank=True, max_length=32)),
                ("carrier_walmart", models.CharField(blank=True, max_length=32)),
                ("tracking_number", models.CharField(db_index=True, max_length=64)),
                ("ship_date", models.DateTimeField(blank=True, null=True)),
                ("estimated_delivery", models.DateTimeField(blank=True, null=True)),
                ("items", models.JSONField(default=list)),
                ("upload_hash", models.CharField(max_length=48, unique=True)),
                ("uploaded_to_walmart_at", models.DateTimeField(blank=True, null=True)),
                ("upload_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mcf_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="walmart_mcf.amazonmcforder",
                    ),
                ),
            ],
            options={
                "db_table": "wm_shipment_packages",
            },
        ),
        migrations.CreateModel(
            name="SkuMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("walmart_sku", models.CharField(max_length=64, unique=True)),
                ("amazon_sku", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=256)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SKU Mapping",
                "db_table": "wm_sku_mappings",
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(blank=True, max_length=256)),
                ("exception", models.CharField(max_length=256)),
                ("stack_trace", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="walmart_mcf.walmartorder",
                    ),
                ),
            ],
            options={
                "db_table": "wm_error_logs",
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_state", models.CharField(blank=True, max_length=24)),
                ("to_state", models.CharField(max_length=24)),
                ("actor", models.CharField(max_length=64)),
                ("detail", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="walmart_mcf.walmartorder",
                    ),
                ),
            ],
            options={
                "db_table": "wm_audit_events",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="amazonmcforder",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mcf",
                to="walmart_mcf.walmartorder",
            ),
        ),
        migrations.CreateModel(
            name="WalmartOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.CharField(max_length=8)),
                ("walmart_sku", models.CharField(db_index=True, max_length=64)),
                ("product_name", models.CharField(blank=True, max_length=256)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="walmart_mcf.walmartorder",
                    ),
                ),
            ],
            options={
                "db_table": "wm_order_items",
                "unique_together": {("order", "line_number")},
            },
        ),
    ]
