# Generated by Django 5.0.6 on 2026-07-13 11:19

import apps.amazon_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walmart_mcf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalmartAPIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(default="Walmart US Marketplace", max_length=64),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client_id",
                    apps.amazon_api.models.EncryptedField(
                        blank=True, help_text="Walmart Client ID"
                    ),
                ),
                (
                    "client_secret",
                    apps.amazon_api.models.EncryptedField(
                        blank=True, help_text="Walmart Client Secret"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Walmart API Configuration",
                "db_table": "wm_api_config",
            },
        ),
    ]
