# Generated by Django 5.0.6 on 2026-07-16 11:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AtlasCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("currency", models.CharField(default="AED", max_length=3)),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.05"), max_digits=5
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Atlas companies",
                "db_table": "atlas_companies",
            },
        ),
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("days", models.PositiveIntegerField(default=0)),
                ("advance_pct", models.PositiveIntegerField(default=0)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "atlas_payment_terms",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="AtlasCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("contact_person", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("address", models.TextField(blank=True)),
                (
                    "trn",
                    models.CharField(
                        blank=True, help_text="Tax registration number", max_length=32
                    ),
                ),
                (
                    "kg_rate_local",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "kg_rate_container",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "terms_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Customer-specific T&Cs shown on documents",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="atlas.atlascompany",
                    ),
                ),
                (
                    "default_payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="atlas.paymentterm",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_customers",
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="AtlasProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=200)),
                ("length_cm", models.DecimalField(decimal_places=2, max_digits=8)),
                ("width_cm", models.DecimalField(decimal_places=2, max_digits=8)),
                ("gsm", models.PositiveIntegerField()),
                ("yarn", models.CharField(blank=True, max_length=60)),
                ("size_label", models.CharField(blank=True, max_length=60)),
                ("colour", models.CharField(blank=True, max_length=60)),
                (
                    "dyeing",
                    models.CharField(
                        blank=True,
                        choices=[("vat", "VAT"), ("reactive", "Reactive")],
                        max_length=12,
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plain", "Plain"),
                            ("dobby", "Dobby"),
                            ("jacquard", "Jacquard"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Quality family used as the first selector in quotation creation",
                        max_length=80,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Unit cost (from RFQ/inventory)",
                        max_digits=12,
                    ),
                ),
                ("stock_qty", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="atlas.atlascompany",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_products",
                "ordering": ["sku"],
                "unique_together": {("company", "sku")},
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=24, unique=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("local", "Local Order"),
                            ("container", "Container Order"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "container_type",
                    models.CharField(
                        blank=True,
                        choices=[("fob", "FOB"), ("cnf", "CNF"), ("ddp", "DDP")],
                        max_length=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=8,
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=3, default=0, max_digits=6),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("expected_delivery", models.DateField(blank=True, null=True)),
                ("is_sample_request", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True)),
                ("lost_reason", models.CharField(blank=True, max_length=200)),
                ("has_stock_shortage", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="atlas.atlascompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="atlas.atlascustomer",
                    ),
                ),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="atlas.paymentterm",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_quotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NegativeStockLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_short", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atlas.atlascompany",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atlas.atlasproduct",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negative_stock",
                        to="atlas.quotation",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_negative_stock_log",
            },
        ),
        migrations.CreateModel(
            name="QuotationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "kg_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "weight_kg",
                    models.DecimalField(decimal_places=5, default=0, max_digits=10),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "discount_pct",
                    models.DecimalField(decimal_places=3, default=0, max_digits=6),
                ),
                ("stock_short", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.atlasproduct",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="atlas.quotation",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_quotation_lines",
            },
        ),
        migrations.CreateModel(
            name="CustomerKgRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("local", "Local Order"),
                            ("container", "Container Order"),
                        ],
                        max_length=12,
                    ),
                ),
                ("kg_rate", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kg_rate_overrides",
                        to="atlas.atlascustomer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atlas.atlasproduct",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_customer_kg_rates",
                "unique_together": {("customer", "product", "order_type")},
            },
        ),
        migrations.CreateModel(
            name="QuotationRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("change_note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="atlas.quotation",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_quotation_revisions",
                "ordering": ["number"],
                "unique_together": {("quotation", "number")},
            },
        ),
    ]
