# Generated by Django 5.0.6 on 2026-07-17 01:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="atlasproduct",
            name="is_peak",
            field=models.BooleanField(
                default=False, help_text="Peak/seasonal mode active for this article"
            ),
        ),
        migrations.AddField(
            model_name="atlasproduct",
            name="peak_multiplier",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("1.5"),
                help_text="Demand multiplier applied while peak mode is on",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="atlasproduct",
            name="production_lead_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="atlasproduct",
            name="sell_through_daily",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Average units sold per day",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="atlasproduct",
            name="shipment_lead_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AtlasSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("country", models.CharField(blank=True, max_length=60)),
                ("contact", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="atlas.atlascompany",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_suppliers",
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=24, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("received", "Received"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="atlas.atlascompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="For customer-backed container POs",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="atlas.atlascustomer",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to="atlas.quotation",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to="atlas.atlassupplier",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_purchase_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Backorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atlas.atlascompany",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backorders",
                        to="atlas.atlascustomer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atlas.atlasproduct",
                    ),
                ),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backorders",
                        to="atlas.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_backorders",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("qty_received", models.PositiveIntegerField(default=0)),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="atlas.purchaseorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atlas.atlasproduct",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_po_lines",
            },
        ),
        migrations.CreateModel(
            name="RFQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=24, unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Free text when no product exists yet",
                        max_length=200,
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=60)),
                ("gsm", models.PositiveIntegerField(blank=True, null=True)),
                ("construction", models.CharField(blank=True, max_length=120)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "port",
                    models.CharField(
                        blank=True,
                        help_text="Port/city inventory ships from",
                        max_length=80,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, upload_to="atlas_rfq/%Y/%m/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open — awaiting response"),
                            ("responded", "Responded"),
                            ("revalidation", "Revalidation requested"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=14,
                    ),
                ),
                (
                    "revalidation_requested_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfqs",
                        to="atlas.atlascompany",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfqs",
                        to="atlas.atlascustomer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Existing article, if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="atlas.atlasproduct",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "atlas_rfqs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="POStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=80)),
                ("tat_days", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("alerted", models.BooleanField(default=False)),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="atlas.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_po_stages",
                "ordering": ["sequence"],
                "unique_together": {("po", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="RFQResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[("budgetary", "Budgetary"), ("actual", "Actual")],
                        default="actual",
                        max_length=10,
                    ),
                ),
                (
                    "manufacturer_construction",
                    models.CharField(blank=True, max_length=120),
                ),
                ("moq", models.PositiveIntegerField(blank=True, null=True)),
                ("lead_time_days", models.PositiveIntegerField(blank=True, null=True)),
                ("inquiry_date", models.DateField(blank=True, null=True)),
                ("request_date", models.DateField(blank=True, null=True)),
                ("rates_received_date", models.DateField(blank=True, null=True)),
                (
                    "fob_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "cnf_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "ddp_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "vendor_kg_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("applied_to_cost", models.BooleanField(default=False)),
                ("applied_rate", models.CharField(blank=True, max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="atlas.rfq",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_rfq_responses",
                "ordering": ["number"],
                "unique_together": {("rfq", "number")},
            },
        ),
    ]
