# Generated by Django 5.0.6 on 2026-07-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="perm_overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
