from django.urls import path

from . import views

app_name = 'inventory_planning'

urlpatterns = [
    path('',                 views.planner,        name='planner'),
    path('runway/',          views.runway,         name='runway'),
    path('loading-plan/',    views.loading_plan,   name='loading_plan'),
    path('reorder/',         views.reorder,        name='reorder'),
    path('api/reorder/',     views.api_reorder,    name='api_reorder'),
    path('api/reorder/regenerate/', views.api_reorder_regenerate,
         name='api_reorder_regenerate'),
    path('api/reorder/action/', views.api_reorder_action,
         name='api_reorder_action'),
    path('api/reserve/',     views.api_reserve,    name='api_reserve'),
    path('api/loading-plan/', views.api_loading_plan, name='api_loading_plan'),
    path('loading-plan.xlsx', views.loading_plan_export, name='loading_plan_export'),
    path('containers/',      views.containers,     name='containers'),
    path('receiving/',       views.receiving,      name='receiving'),
    path('container-history/', views.container_history, name='container_history'),
    path('container/<int:pk>/view/', views.container_view, name='container_view'),
    path('api/planner/',     views.api_planner,    name='api_planner'),
    path('api/containers/',  views.api_containers, name='api_containers'),
    path('api/receiving/',   views.api_receiving,  name='api_receiving'),
    path('api/container-history/', views.api_container_history, name='api_container_history'),
    path('api/receive-container/', views.api_receive_container, name='api_receive_container'),
    path('api/container-pickup/', views.api_container_pickup, name='api_container_pickup'),
    path('api/sync-stock/',  views.api_sync_stock, name='api_sync_stock'),
    path('api/save-pds/',    views.save_pds,       name='save_pds'),
    path('api/save-container/', views.save_container, name='save_container'),
    path('api/delete-container/', views.delete_container, name='delete_container'),
    path('api/container/<int:pk>/', views.container_detail, name='container_detail'),
    path('api/warehouses/',  views.warehouses,     name='warehouses'),
    path('import/master/',   views.import_master,  name='import_master'),
    path('import/containers/', views.import_containers_view, name='import_containers'),
    path('import/workbook/', views.import_workbook, name='import_workbook'),
    path('import/pds/',      views.import_pds,     name='import_pds'),
    path('master-template.xlsx', views.master_template, name='master_template'),
    path('container-template.xlsx', views.container_template, name='container_template'),
    path('pds-template.xlsx', views.pds_template,  name='pds_template'),
    path('export.xlsx',      views.export_planner, name='export'),

    # ── Procurement (Phase 2) ──
    path('suppliers/',       views.suppliers,      name='suppliers'),
    path('sourcing/',        views.sourcing,       name='sourcing'),
    path('goods-receipt/',   views.goods_receipt,  name='goods_receipt'),
    path('api/goods-receipt/', views.api_goods_receipt, name='api_goods_receipt'),
    path('api/short-close/', views.api_short_close, name='api_short_close'),
    path('api/receipt-reason/', views.api_receipt_reason, name='api_receipt_reason'),
    path('goods-receipt.xlsx', views.goods_receipt_export, name='goods_receipt_export'),
    path('cashflow/',        views.cashflow,       name='cashflow'),
    path('api/cashflow/',    views.api_cashflow,   name='api_cashflow'),
    path('api/cashflow/refresh/', views.api_cashflow_refresh,
         name='api_cashflow_refresh'),
    path('api/cashflow/opening/', views.api_cashflow_opening,
         name='api_cashflow_opening'),
    path('api/cashflow/entry/', views.api_cashflow_entry,
         name='api_cashflow_entry'),
    path('api/container-freight/', views.api_container_freight,
         name='api_container_freight'),
    path('api/sourcing/',    views.api_sourcing,   name='api_sourcing'),
    path('api/sku-sourcing/', views.api_sku_sourcing, name='api_sku_sourcing'),
    path('purchase-orders/', views.purchase_orders, name='purchase_orders'),
    path('api/suppliers/',   views.api_suppliers,  name='api_suppliers'),
    path('api/supplier/save/', views.api_supplier_save,
         name='api_supplier_save'),
    path('api/supplier/<int:pk>/', views.api_supplier_detail,
         name='api_supplier_detail'),
    path('api/purchase-orders/', views.api_purchase_orders,
         name='api_purchase_orders'),
    path('api/po/<int:pk>/', views.api_po_detail,  name='api_po_detail'),
    path('api/production-plan/<int:pk>/', views.api_production_plan,
         name='api_production_plan'),
    path('import/po/',       views.import_po,      name='import_po'),
    path('import/wastage/',  views.import_wastage_view, name='import_wastage'),
    path('import/opening/',  views.import_opening_view, name='import_opening'),
    path('po-workbook-template.xlsx', views.po_workbook_template,
         name='po_workbook_template'),
    path('opening-balance-template.xlsx', views.opening_balance_template,
         name='opening_balance_template'),
    path('wastage-template.xlsx', views.wastage_template,
         name='wastage_template'),
    path('fba-transfers/',   views.fba_transfers,  name='fba_transfers'),
    path('api/fba-transfers/', views.api_fba_transfers, name='api_fba_transfers'),
    path('api/fba-transfer/save/', views.api_fba_transfer_save,
         name='api_fba_transfer_save'),
    path('api/fba-transfer/action/', views.api_fba_transfer_action,
         name='api_fba_transfer_action'),
    path('api/fba-transfer/delete/', views.api_fba_transfer_delete,
         name='api_fba_transfer_delete'),
    path('api/source-stock/', views.api_source_stock, name='api_source_stock'),
    path('import/fba-transfers/', views.import_fba_transfers_view,
         name='import_fba_transfers'),
    path('fba-transfer-template.xlsx', views.fba_transfer_template,
         name='fba_transfer_template'),
    path('allocation/',      views.allocation,      name='allocation'),
    path('packing-list-template.xlsx', views.packing_list_template,
         name='packing_list_template'),
    path('api/packing/preview/', views.api_packing_preview,
         name='api_packing_preview'),
    path('api/packing/commit/',  views.api_packing_commit,
         name='api_packing_commit'),
    path('api/open-plans/',  views.api_open_plans,  name='api_open_plans'),
]
